import type { ServiceCard, UseCase, OTNode, PlantSite, KPI } from '../types';

export const stakeholderProfiles = {
  CIO: {
    headline: 'From Operational Fragmentation to Industrial Intelligence',
    subhead: 'Transform your factory estate into a governed digital platform that scales autonomously.',
    kpis: ['Operational Cost Reduction', 'MTTR Improvement', 'Deployment Velocity', 'OT Coverage'],
    focus: 'Business value and governance at enterprise scale',
  },
  CTO: {
    headline: 'The Architecture of Autonomous Industrial Systems',
    subhead: 'Build the technical foundation that makes AI-driven operations possible.',
    kpis: ['API Availability', 'Data Pipeline Latency', 'Twin Fidelity', 'Platform Adoption'],
    focus: 'Technical architecture and platform capability',
  },
  PlantManager: {
    headline: 'Every Asset. Every Signal. Every Decision — In Context.',
    subhead: 'Your factory becomes self-aware, self-optimizing, and self-healing.',
    kpis: ['OEE Improvement', 'Unplanned Downtime', 'Energy Per Unit', 'Quality Defect Rate'],
    focus: 'Operational efficiency and production reliability',
  },
  ManufacturingIT: {
    headline: 'OT/IT Convergence Without Compromise',
    subhead: 'Connect industrial systems to digital infrastructure without sacrificing operational stability.',
    kpis: ['IT/OT Integration Points', 'Protocol Coverage', 'Segmentation Health', 'Patch Compliance'],
    focus: 'Integration, security, and operational continuity',
  },
  OTArchitect: {
    headline: 'Purdue-Compliant. Zero Trust. Digitally Native.',
    subhead: 'Design industrial architectures that are observable, governed, and intelligently orchestrated.',
    kpis: ['Zone Compliance', 'DMZ Coverage', 'Protocol Normalization', 'Asset Fingerprint Rate'],
    focus: 'Architecture design, zoning, and standards compliance',
  },
  CISO: {
    headline: 'OT Security Posture Built from Operational Truth',
    subhead: 'Visibility is not optional. Every unknown asset is an unmanaged risk.',
    kpis: ['Unknown Assets', 'Vulnerability Exposure', 'Segmentation Violations', 'Mean Time to Detect'],
    focus: 'Security posture, threat surface, and compliance',
  },
  ReliabilityEngineer: {
    headline: 'Predict. Prevent. Perform.',
    subhead: 'Digital twins that evolve from real operational behavior enable proactive reliability.',
    kpis: ['MTBF Improvement', 'PdM Accuracy', 'False Alarm Rate', 'Maintenance Cost Reduction'],
    focus: 'Asset reliability, predictive maintenance, and failure analysis',
  },
  SustainabilityOfficer: {
    headline: 'Industrial Sustainability Starts with Operational Visibility',
    subhead: 'Carbon optimization requires knowing exactly where energy flows in your factory.',
    kpis: ['Carbon Reduction', 'Energy Intensity', 'Renewable Integration', 'Scope 2 Emissions'],
    focus: 'Energy optimization, carbon reduction, and ESG reporting',
  },
  OperationsLead: {
    headline: 'Operations That Think, Adapt, and Self-Optimize',
    subhead: 'When your factory has operational intelligence, every decision is informed by real context.',
    kpis: ['Throughput Increase', 'Shift Efficiency', 'Incident Response Time', 'Worker Productivity'],
    focus: 'Operational performance and workforce augmentation',
  },
  PlatformEngineeringLead: {
    headline: 'Build Once. Deploy Everywhere. Govern Continuously.',
    subhead: 'A reusable OT platform foundation that accelerates every use case you deliver.',
    kpis: ['Service Deployment Time', 'Reuse Rate', 'Platform Coverage', 'Time to Value'],
    focus: 'Platform scalability, reusability, and developer experience',
  },
};

export const maturityJourney = [
  { id: 'Fragmented', label: 'Fragmented', desc: 'Unknown assets, disconnected systems, zero visibility', color: '#D64545', icon: '⚠' },
  { id: 'Visible', label: 'Visible', desc: 'Asset discovery, topology mapping, protocol awareness', color: '#F5A623', icon: '👁' },
  { id: 'Contextual', label: 'Contextual', desc: 'Semantic relationships, operational knowledge graph', color: '#00A3E0', icon: '🔗' },
  { id: 'Intelligent', label: 'Intelligent', desc: 'Digital twins, AI-assisted operations, predictive insights', color: '#005EB8', icon: '🧠' },
  { id: 'Autonomous', label: 'Autonomous', desc: 'Self-healing systems, autonomous orchestration, zero-touch', color: '#12B3A8', icon: '⚡' },
];

// Purdue levels: L4 Enterprise at TOP (low y%), L0 Field at BOTTOM (high y%)
// L4 ~8%, L3 ~25%, DMZ ~42%, L2 ~58%, L1 ~74%, L0 ~90%
export const otNodes: OTNode[] = [
  { id: 'cloud1', label: 'AWS IoT Core', type: 'Cloud', status: 'online', zone: 'Level4', x: 50, y: 8, protocol: 'MQTT/TLS' },
  { id: 'hist1', label: 'OSIsoft PI', type: 'Server', status: 'online', zone: 'Level3', x: 30, y: 25, vendor: 'OSIsoft', protocol: 'PI API' },
  { id: 'mes1', label: 'MES Platform', type: 'Server', status: 'online', zone: 'Level3', x: 65, y: 25, vendor: 'SAP ME', protocol: 'REST' },
  { id: 'net1', label: 'OT Firewall', type: 'Network', status: 'online', zone: 'DMZ', x: 50, y: 42, vendor: 'Fortinet' },
  { id: 'hmi1', label: 'HMI Station A', type: 'HMI', status: 'online', zone: 'Level2', x: 18, y: 58, vendor: 'Wonderware', protocol: 'OPC-DA' },
  { id: 'hmi2', label: 'HMI Station B', type: 'HMI', status: 'offline', zone: 'Level2', x: 48, y: 58, vendor: 'Ignition', protocol: 'OPC-UA' },
  { id: 'plc1', label: 'PLC Line 1', type: 'PLC', status: 'online', zone: 'Level1', x: 18, y: 74, vendor: 'Siemens', protocol: 'S7', firmware: '2.8.1' },
  { id: 'plc2', label: 'PLC Line 2', type: 'PLC', status: 'warning', zone: 'Level1', x: 50, y: 74, vendor: 'Rockwell', protocol: 'EtherNet/IP', firmware: '1.4.0' },
  { id: 'plc3', label: 'PLC Utilities', type: 'PLC', status: 'critical', zone: 'Level1', x: 80, y: 74, vendor: 'ABB', protocol: 'Modbus', firmware: '0.9.2', vulnerabilities: 3 },
  { id: 'sensor1', label: 'Vibration Array', type: 'Sensor', status: 'online', zone: 'Level0', x: 10, y: 90, protocol: 'IO-Link' },
  { id: 'sensor2', label: 'Thermal Sensor', type: 'Sensor', status: 'warning', zone: 'Level0', x: 33, y: 90, protocol: 'HART' },
  { id: 'sensor3', label: 'Flow Meter', type: 'Sensor', status: 'unknown', zone: 'Level0', x: 60, y: 90, protocol: 'Modbus RTU' },
  { id: 'sensor4', label: 'Pressure Grid', type: 'Sensor', status: 'online', zone: 'Level0', x: 82, y: 90, protocol: 'IO-Link' },
];

export const serviceCards: ServiceCard[] = [
  { id: 'connectivity', name: 'OT Connectivity Hub', category: 'Connectivity', description: 'Unified protocol translation — Modbus, OPC-UA, MQTT, EtherNet/IP, S7, HART bridged into a normalized data fabric.', icon: '🔌', kpiImpact: ['Protocol Coverage', 'Data Latency', 'Integration Cost'], maturityRequired: 'Visible', deploymentComplexity: 'Medium', edgeSplit: 70, cloudSplit: 30, twinIntegration: true },
  { id: 'ot-security', name: 'OT Security Posture', category: 'Security', description: 'IEC 62443 compliant segmentation, passive deep-packet inspection, Zero Trust network access for OT environments.', icon: '🛡', kpiImpact: ['Unknown Assets', 'Vulnerability Exposure', 'Compliance Score'], maturityRequired: 'Visible', deploymentComplexity: 'High', edgeSplit: 60, cloudSplit: 40, twinIntegration: false },
  { id: 'asset-mgmt', name: 'OT Asset Management', category: 'Asset Visibility', description: 'Auto-discovery, fingerprinting, CMDB population, firmware tracking, and lifecycle governance for every OT asset.', icon: '📋', kpiImpact: ['Asset Coverage', 'Firmware Compliance', 'MTTR'], maturityRequired: 'Visible', deploymentComplexity: 'Low', edgeSplit: 40, cloudSplit: 60, twinIntegration: true },
  { id: 'backup-recovery', name: 'OT Backup & Recovery', category: 'Backup & Recovery', description: 'Automated PLC/HMI configuration backup, version control, rapid restore for operational continuity.', icon: '💾', kpiImpact: ['RTO', 'Config Compliance', 'Recovery Success Rate'], maturityRequired: 'Visible', deploymentComplexity: 'Low', edgeSplit: 50, cloudSplit: 50, twinIntegration: false },
  { id: 'pam', name: 'OT Privileged Access', category: 'PAM', description: 'Vendor-agnostic privileged access management with session recording, just-in-time access, and full audit trails.', icon: '🔐', kpiImpact: ['Unauthorized Access', 'Audit Coverage', 'Vendor Risk'], maturityRequired: 'Visible', deploymentComplexity: 'Medium', edgeSplit: 20, cloudSplit: 80, twinIntegration: false },
  { id: 'ot-ad', name: 'OT Active Directory', category: 'OT Active Directory', description: 'Industrial identity services designed for OT — role-based access, machine identity, operational zones, workforce provisioning.', icon: '🏛', kpiImpact: ['Identity Coverage', 'Zone Compliance', 'Provisioning Time'], maturityRequired: 'Contextual', deploymentComplexity: 'High', edgeSplit: 30, cloudSplit: 70, twinIntegration: false },
  { id: 'monitoring', name: 'Centralized OT Monitoring', category: 'Monitoring', description: 'Real-time telemetry aggregation from all levels — Purdue L0-L4, anomaly detection, operational alerting.', icon: '📡', kpiImpact: ['MTTD', 'Alert Accuracy', 'Coverage Ratio'], maturityRequired: 'Visible', deploymentComplexity: 'Medium', edgeSplit: 40, cloudSplit: 60, twinIntegration: true },
  { id: 'patch-mgmt', name: 'OT Patch Management', category: 'Patch Management', description: 'Risk-aware patch scheduling that respects operational windows, validates firmware integrity, and maintains uptime.', icon: '🔧', kpiImpact: ['Patch Compliance', 'CVE Exposure', 'Maintenance Cost'], maturityRequired: 'Contextual', deploymentComplexity: 'High', edgeSplit: 30, cloudSplit: 70, twinIntegration: false },
  { id: 'remote-access', name: 'Secure Remote Access', category: 'Remote Access', description: 'Zero Trust remote access for OT with session recording, conditional access, and vendor isolation.', icon: '🌐', kpiImpact: ['Vendor Incidents', 'Remote Efficiency', 'Compliance'], maturityRequired: 'Visible', deploymentComplexity: 'Medium', edgeSplit: 20, cloudSplit: 80, twinIntegration: false },
  { id: 'dpp', name: 'Digital Product Passport', category: 'DPP', description: 'Regulatory-grade digital product lifecycle tracking from raw material to end-of-life — EU DPP compliant.', icon: '📄', kpiImpact: ['Regulatory Compliance', 'Supply Chain Visibility', 'Carbon Traceability'], maturityRequired: 'Intelligent', deploymentComplexity: 'High', edgeSplit: 10, cloudSplit: 90, twinIntegration: true },
  { id: 'sustainability', name: 'Sustainability Intelligence', category: 'Sustainability', description: 'Real-time Scope 1/2/3 emissions tracking, energy optimization, carbon twin simulation, ESG reporting.', icon: '🌱', kpiImpact: ['Carbon Reduction', 'Energy Intensity', 'ESG Score'], maturityRequired: 'Intelligent', deploymentComplexity: 'Medium', edgeSplit: 30, cloudSplit: 70, twinIntegration: true },
  { id: 'predictive-maint', name: 'Predictive Maintenance', category: 'Predictive Maintenance', description: 'ML-based failure prediction using vibration, thermal, acoustic, and operational signatures at the asset level.', icon: '🔮', kpiImpact: ['MTBF', 'Unplanned Downtime', 'Maintenance Cost'], maturityRequired: 'Intelligent', deploymentComplexity: 'Medium', edgeSplit: 50, cloudSplit: 50, twinIntegration: true },
  { id: 'ai-quality', name: 'AI Quality Inspection', category: 'AI Quality Inspection', description: 'Computer vision defect detection at line speed — zero sampling bias, full traceability, process correlation.', icon: '🔬', kpiImpact: ['Defect Rate', 'Scrap Cost', 'Customer Returns'], maturityRequired: 'Intelligent', deploymentComplexity: 'High', edgeSplit: 80, cloudSplit: 20, twinIntegration: true },
  { id: 'carbon-opt', name: 'Carbon Optimization Engine', category: 'Carbon Optimization', description: 'Closed-loop carbon control — real-time tracking, process optimization recommendations, offset intelligence.', icon: '♻', kpiImpact: ['Scope 1 Emissions', 'Energy Cost', 'Carbon Credits'], maturityRequired: 'Autonomous', deploymentComplexity: 'High', edgeSplit: 30, cloudSplit: 70, twinIntegration: true },
  { id: 'root-cause', name: 'Root Cause Intelligence', category: 'Root Cause Intelligence', description: 'AI-driven causal analysis across the operational graph — correlates topology, telemetry, and maintenance history.', icon: '🧩', kpiImpact: ['MTTR', 'Repeat Incidents', 'Investigation Cost'], maturityRequired: 'Intelligent', deploymentComplexity: 'Medium', edgeSplit: 20, cloudSplit: 80, twinIntegration: true },
  { id: 'factory-copilot', name: 'Factory Copilot', category: 'Factory Copilot', description: 'Conversational AI over your operational graph — query your factory in natural language, get contextual insights.', icon: '🤖', kpiImpact: ['Decision Velocity', 'Operator Productivity', 'Knowledge Retention'], maturityRequired: 'Autonomous', deploymentComplexity: 'Medium', edgeSplit: 10, cloudSplit: 90, twinIntegration: true },
  { id: 'worker-safety', name: 'Worker Safety Twin', category: 'Worker Safety Twin', description: 'Real-time ergonomic risk, environmental exposure, fatigue modeling, and proximity intelligence for workforce safety.', icon: '👷', kpiImpact: ['Safety Incidents', 'Compliance Cost', 'Worker Wellbeing'], maturityRequired: 'Intelligent', deploymentComplexity: 'Medium', edgeSplit: 60, cloudSplit: 40, twinIntegration: true },
];

export const useCases: UseCase[] = [
  {
    id: 'predictive-maintenance',
    title: 'Predictive Maintenance',
    description: 'Detect failure signatures before breakdown using asset twin behavioral models.',
    inputs: ['Vibration Sensors', 'Thermal Cameras', 'Current Signatures', 'Historical Maintenance'],
    edgeProcessing: ['Signal Filtering', 'Feature Extraction', 'Anomaly Pre-scoring', 'Local Alert'],
    cloudAnalytics: ['AWS Lookout for Equipment', 'Digital Twin State', 'Failure Pattern Library', 'Fleet Benchmarking'],
    decisionLogic: ['Failure Probability Score', 'Maintenance Window Selection', 'Parts Procurement Trigger', 'Operator Notification'],
    outcomes: ['Maintenance Ticket', 'Work Order Creation', 'Part Pre-staging', 'Downtime Avoidance'],
    roi: '35% reduction in unplanned downtime',
    complexity: 'Medium',
    maturityRequired: 'Intelligent',
    industries: ['Automotive', 'Energy', 'Mining', 'Food & Beverage'],
  },
  {
    id: 'autonomous-condition-monitoring',
    title: 'Autonomous Condition Monitoring',
    description: 'Continuous asset health scoring with zero human intervention — self-adjusting thresholds.',
    inputs: ['Vibration', 'Temperature', 'Pressure', 'Flow Rate', 'Power Consumption'],
    edgeProcessing: ['Edge ML Inference', 'Threshold Adaptation', 'Local State Machine', 'Buffering'],
    cloudAnalytics: ['AWS SiteWise', 'Time-Series DB', 'Baseline Learning', 'Peer Comparison'],
    decisionLogic: ['Health Score Engine', 'Degradation Trajectory', 'Intervention Priority Queue'],
    outcomes: ['Health Dashboard Update', 'Alert Escalation', 'Autonomous Schedule Adjustment', 'Twin State Update'],
    roi: '28% improvement in OEE',
    complexity: 'Medium',
    maturityRequired: 'Intelligent',
    industries: ['Process', 'Discrete', 'Utilities'],
  },
  {
    id: 'carbon-optimization',
    title: 'Carbon Optimization',
    description: 'Closed-loop carbon control that balances production targets with emissions constraints in real time.',
    inputs: ['Energy Meters', 'Production Schedule', 'Grid Carbon Intensity', 'Process Parameters'],
    edgeProcessing: ['Energy Disaggregation', 'Scope 1 Calculation', 'Local Carbon Buffer'],
    cloudAnalytics: ['Carbon Twin', 'Grid API Integration', 'Simulation Engine', 'Offset Marketplace'],
    decisionLogic: ['Emission Budget Allocation', 'Production Scheduling Optimization', 'Renewable Shift Logic'],
    outcomes: ['Schedule Adjustment', 'Carbon Report', 'Offset Recommendation', 'ESG Dashboard Update'],
    roi: '22% reduction in Scope 1 emissions',
    complexity: 'High',
    maturityRequired: 'Intelligent',
    industries: ['Steel', 'Cement', 'Chemical', 'Energy'],
  },
  {
    id: 'digital-product-passport',
    title: 'Digital Product Passport',
    description: 'EU DPP-compliant traceability from raw material to end-of-life embedded in every product.',
    inputs: ['Material Origin', 'Process Parameters', 'Quality Data', 'Energy Consumption', 'Worker Records'],
    edgeProcessing: ['Data Capture at Line', 'Timestamp Anchoring', 'Local Validation'],
    cloudAnalytics: ['Blockchain Anchoring', 'Regulatory Mapping', 'Sustainability Calculator'],
    decisionLogic: ['Compliance Gate', 'Pass/Fail Scoring', 'Remediation Trigger'],
    outcomes: ['DPP Certificate', 'Regulatory Submission', 'Customer Transparency Portal', 'Recall Traceability'],
    roi: 'EU market access + 15% premium pricing',
    complexity: 'High',
    maturityRequired: 'Intelligent',
    industries: ['Automotive', 'Electronics', 'Textiles', 'Battery'],
  },
  {
    id: 'worker-safety-twin',
    title: 'Worker Safety Twin',
    description: 'Real-time digital twin of the human-machine environment for proactive safety management.',
    inputs: ['Wearable Biometrics', 'Vision AI', 'Zone Presence', 'Environmental Sensors', 'Equipment State'],
    edgeProcessing: ['Fatigue Detection', 'Proximity Alert', 'PPE Compliance Check'],
    cloudAnalytics: ['Safety Twin', 'Incident Pattern Analysis', 'Regulatory Reporting', 'Training Gap Analysis'],
    decisionLogic: ['Risk Score Engine', 'Intervention Trigger', 'Autonomous Zone Access Control'],
    outcomes: ['Safety Alert', 'Equipment Slowdown', 'Supervisor Notification', 'Insurance Reporting'],
    roi: '60% reduction in recordable incidents',
    complexity: 'Medium',
    maturityRequired: 'Intelligent',
    industries: ['Mining', 'Construction', 'Chemical', 'Automotive'],
  },
  {
    id: 'ai-quality-inspection',
    title: 'AI Quality Inspection',
    description: 'Computer vision at line speed with zero sampling bias and full defect traceability to process root cause.',
    inputs: ['Line Cameras', 'Process Parameters', 'Material Specs', 'Historical Defect Library'],
    edgeProcessing: ['Real-Time Inference', 'Defect Classification', 'Local Decision', 'Reject Trigger'],
    cloudAnalytics: ['Model Retraining', 'Defect Trend Analysis', 'Process Correlation', 'SPC Integration'],
    decisionLogic: ['Defect Gate', 'Process Parameter Recommendation', 'Escalation Logic'],
    outcomes: ['Accept/Reject Signal', 'Process Adjustment', 'Quality Report', 'Supplier Feedback'],
    roi: '73% reduction in customer defect escapes',
    complexity: 'High',
    maturityRequired: 'Intelligent',
    industries: ['Automotive', 'Electronics', 'Pharma', 'Food & Beverage'],
  },
  {
    id: 'factory-as-a-service',
    title: 'Factory-as-a-Service',
    description: 'Expose factory capacity as a digital service — demand-driven production with full digital orchestration.',
    inputs: ['Customer Orders', 'Capacity Twin', 'Resource State', 'Quality Standards'],
    edgeProcessing: ['Capacity Sensing', 'Constraint Detection', 'Local Scheduling'],
    cloudAnalytics: ['Production Optimization', 'Digital Marketplace', 'SLA Tracking'],
    decisionLogic: ['Dynamic Scheduling', 'Constraint Resolution', 'Pricing Engine'],
    outcomes: ['Order Confirmation', 'Production Schedule', 'Customer Portal Update', 'Revenue Recognition'],
    roi: '40% increase in asset utilization',
    complexity: 'High',
    maturityRequired: 'Autonomous',
    industries: ['Electronics', 'Automotive', 'Aerospace'],
  },
  {
    id: 'heat-exchanger-optimization',
    title: 'Heat Exchanger Optimization',
    description: 'Thermal efficiency twin that continuously optimizes cleaning schedules and operating setpoints.',
    inputs: ['Temperature Differential', 'Flow Rate', 'Pressure Drop', 'Fouling Sensors'],
    edgeProcessing: ['Efficiency Calculation', 'Fouling Rate Detection', 'Local Optimization Loop'],
    cloudAnalytics: ['Thermal Twin', 'Cleaning Schedule Optimizer', 'Energy Benchmarking'],
    decisionLogic: ['Cleaning Trigger', 'Setpoint Recommendation', 'Shutdown Risk Assessment'],
    outcomes: ['Cleaning Work Order', 'Setpoint Update', 'Energy Saving Report', 'Capital Deferral'],
    roi: '18% energy savings + 30% cleaning cost reduction',
    complexity: 'Low',
    maturityRequired: 'Intelligent',
    industries: ['Chemical', 'Oil & Gas', 'Power', 'Food & Beverage'],
  },
  {
    id: 'root-cause-intelligence',
    title: 'Root Cause Intelligence',
    description: 'AI-powered causal chain analysis that traverses the operational graph to find true failure origin.',
    inputs: ['Alarm Storm Data', 'Topology Graph', 'Maintenance History', 'Process Parameters'],
    edgeProcessing: ['Alarm Suppression', 'First Principle Detection', 'Causal Candidate Extraction'],
    cloudAnalytics: ['Graph Neural Network', 'Causal Model Library', 'Historical Pattern Match'],
    decisionLogic: ['Root Cause Ranking', 'Confidence Scoring', 'Corrective Action Library'],
    outcomes: ['RCA Report', 'CAPA Generation', 'CMDB Update', 'Knowledge Graph Enrichment'],
    roi: '55% reduction in MTTR',
    complexity: 'Medium',
    maturityRequired: 'Intelligent',
    industries: ['Process', 'Energy', 'Pharma', 'Utilities'],
  },
  {
    id: 'green-hydrogen-twin',
    title: 'Green Hydrogen Twin',
    description: 'Electrolyzer digital twin that optimizes hydrogen production against renewable energy availability.',
    inputs: ['Renewable Energy Signal', 'Grid Intensity', 'Electrolyzer State', 'Storage Level'],
    edgeProcessing: ['Stack Performance Model', 'Efficiency Calculation', 'Degradation Tracking'],
    cloudAnalytics: ['Energy Market Integration', 'Production Twin', 'Hydrogen Quality Model'],
    decisionLogic: ['Production Rate Optimization', 'Stack Switch Logic', 'Market Dispatch Decision'],
    outcomes: ['Production Schedule', 'Grid Signal Response', 'Hydrogen Quality Certificate', 'Carbon Report'],
    roi: '25% reduction in levelized cost of hydrogen',
    complexity: 'High',
    maturityRequired: 'Autonomous',
    industries: ['Energy', 'Steel', 'Chemical', 'Transport'],
  },
];

export const plantSites: PlantSite[] = [
  { id: 'sg1', name: 'Singapore Plant', location: 'Jurong Island', country: 'Singapore', lat: 1.26, lng: 103.67, maturity: 'Intelligent', assets: 4280, incidents: 2, compliance: 94, activeTwins: 12 },
  { id: 'de1', name: 'Stuttgart Werk', location: 'Stuttgart', country: 'Germany', lat: 48.78, lng: 9.18, maturity: 'Autonomous', assets: 6100, incidents: 0, compliance: 99, activeTwins: 28 },
  { id: 'us1', name: 'Detroit Assembly', location: 'Detroit, MI', country: 'USA', lat: 42.33, lng: -83.05, maturity: 'Contextual', assets: 3400, incidents: 5, compliance: 78, activeTwins: 6 },
  { id: 'cn1', name: 'Shenzhen Factory', location: 'Shenzhen', country: 'China', lat: 22.54, lng: 114.06, maturity: 'Visible', assets: 5200, incidents: 8, compliance: 71, activeTwins: 3 },
  { id: 'in1', name: 'Pune Hub', location: 'Pune', country: 'India', lat: 18.52, lng: 73.86, maturity: 'Fragmented', assets: 1800, incidents: 14, compliance: 52, activeTwins: 0 },
  { id: 'br1', name: 'São Paulo Works', location: 'São Paulo', country: 'Brazil', lat: -23.55, lng: -46.63, maturity: 'Visible', assets: 2100, incidents: 6, compliance: 68, activeTwins: 2 },
  { id: 'uk1', name: 'Manchester Mill', location: 'Manchester', country: 'UK', lat: 53.48, lng: -2.24, maturity: 'Contextual', assets: 2900, incidents: 3, compliance: 85, activeTwins: 7 },
];

export const cioKPIs: KPI[] = [
  { label: 'OT Asset Visibility', value: '94', unit: '%', trend: 'up', delta: '+31%' },
  { label: 'Unplanned Downtime', value: '2.1', unit: 'hrs/mo', trend: 'down', delta: '-68%' },
  { label: 'MTTR', value: '47', unit: 'min', trend: 'down', delta: '-55%' },
  { label: 'OT Maturity Score', value: '7.8', unit: '/10', trend: 'up', delta: '+4.2' },
  { label: 'Deployment Velocity', value: '3.2', unit: 'days/service', trend: 'down', delta: '-82%' },
  { label: 'Sustainability Score', value: '82', unit: '%', trend: 'up', delta: '+28%' },
  { label: 'Active Digital Twins', value: '58', unit: 'twins', trend: 'up', delta: '+52' },
  { label: 'Operational Resilience', value: '96', unit: '%', trend: 'up', delta: '+22%' },
];

export const fragmentationProblems = [
  { id: 'unknown', label: 'Unknown Devices', severity: 'critical', count: '847', icon: '❓' },
  { id: 'shadow-ot', label: 'Shadow OT', severity: 'critical', count: '143', icon: '👻' },
  { id: 'stale-cmdb', label: 'Stale CMDB Records', severity: 'warning', count: '2,341', icon: '📊' },
  { id: 'unsupported', label: 'Unsupported Protocols', severity: 'warning', count: '31', icon: '🔌' },
  { id: 'dup-signals', label: 'Duplicate Signals', severity: 'warning', count: '1,204', icon: '🔁' },
  { id: 'dark-zones', label: 'Dark Operational Zones', severity: 'critical', count: '8', icon: '🌑' },
  { id: 'disconnected', label: 'Disconnected PLCs', severity: 'critical', count: '67', icon: '⚡' },
  { id: 'stale-fw', label: 'EOL Firmware', severity: 'warning', count: '312', icon: '⚠' },
];

export const visibilityCapabilities = [
  { id: 'discovery', label: 'OT Asset Discovery', desc: 'Passive network scanning with zero operational impact', kpi: '98% asset coverage', icon: '🔍' },
  { id: 'cmdb', label: 'OT CMDB', desc: 'Auto-populated, always-current asset registry', kpi: '100% sync accuracy', icon: '📋' },
  { id: 'fingerprint', label: 'Device Fingerprinting', desc: 'Vendor, firmware, and behavior-based identity', kpi: '847 vendors supported', icon: '🪪' },
  { id: 'monitoring', label: 'OT Monitoring', desc: 'Real-time telemetry from all Purdue levels', kpi: '<500ms latency', icon: '📡' },
  { id: 'drift', label: 'Drift Detection', desc: 'Configuration change detection with audit trail', kpi: '100ms detection', icon: '📏' },
  { id: 'protocol', label: 'Protocol Awareness', desc: '150+ industrial protocols decoded and normalized', kpi: '150+ protocols', icon: '🔌' },
  { id: 'segmentation', label: 'Network Segmentation', desc: 'Purdue/IEC 62443 zone mapping and enforcement', kpi: 'Zone compliance: 99%', icon: '🏗' },
  { id: 'dmz', label: 'OT DMZ Visibility', desc: 'Full visibility into IT/OT convergence points', kpi: 'DMZ coverage: 100%', icon: '🚪' },
];

export const twinTypes = [
  { id: 'asset', label: 'Asset Twin', desc: 'Individual equipment — motor, pump, heat exchanger', color: '#005EB8', icon: '⚙' },
  { id: 'process', label: 'Process Twin', desc: 'Production line or chemical process simulation', color: '#00A3E0', icon: '🔄' },
  { id: 'factory', label: 'Factory Twin', desc: 'Complete facility with all systems and flows', color: '#12B3A8', icon: '🏭' },
  { id: 'carbon', label: 'Carbon Twin', desc: 'Real-time emissions model with optimization loops', color: '#34D399', icon: '🌱' },
  { id: 'worker', label: 'Worker Twin', desc: 'Workforce safety, ergonomics, and productivity', color: '#F5A623', icon: '👷' },
  { id: 'sustainability', label: 'Sustainability Twin', desc: 'ESG metrics, energy flows, circular economy', color: '#10B981', icon: '♻' },
  { id: 'operational', label: 'Operational Twin', desc: 'Live operational state with autonomous control loops', color: '#003B73', icon: '🧠' },
];

export const autonomousScenarios = [
  {
    id: 'vibration',
    title: 'Vibration Anomaly',
    trigger: 'Vibration spike detected: 4.2g on Motor B-7',
    steps: [
      'Topology correlation: Motor B-7 → Line 3 → Assembly Cell 4',
      'Impact evaluation: 340 units/hr at risk',
      'Twin simulation: 87% failure probability in 4.2 hours',
      'Remediation: Schedule PdM window at 06:00 shift change',
      'Parts staging: Bearing assembly pre-ordered from CMMS',
      'Operator notification: Maintenance lead + Shift supervisor',
      'Twin updated: Failure averted, health score restored',
    ],
    outcome: 'Downtime avoided. Estimated saving: $47,000',
    severity: 'warning',
    icon: '📳',
  },
  {
    id: 'unauthorized',
    title: 'Unauthorized Device',
    trigger: 'Unknown device detected: 192.168.12.87 in Zone 2',
    steps: [
      'Device fingerprinting: Unknown Windows XP endpoint',
      'Zone policy check: IEC 62443 violation — Level 1 boundary',
      'Network isolation: Port blocked within 90ms',
      'CISO alert: Incident ticket #OT-2847 created',
      'Topology impact: 0 production disruption (isolated)',
      'Forensics initiated: Device captured for analysis',
      'Policy updated: New detection signature added',
    ],
    outcome: 'Threat contained. Zero production impact.',
    severity: 'critical',
    icon: '🚨',
  },
  {
    id: 'energy',
    title: 'Energy Anomaly',
    trigger: 'Compressor A energy consumption +31% above baseline',
    steps: [
      'Baseline comparison: 187 kW vs. 143 kW expected',
      'Process correlation: Suction pressure drop detected',
      'Carbon twin update: +12 tCO₂ projected this shift',
      'Root cause: Filter fouling — efficiency degraded 23%',
      'Recommendation: Cleaning at next planned shutdown',
      'Process adjustment: Setpoint optimized to -8% energy',
      'ESG dashboard: Scope 1 forecast recalculated',
    ],
    outcome: 'Energy waste recovered. €3,200/day saved.',
    severity: 'warning',
    icon: '⚡',
  },
  {
    id: 'overheating',
    title: 'Thermal Overrun',
    trigger: 'Spindle temperature 92°C — 15°C above threshold',
    steps: [
      'Thermal twin activated: Degradation model running',
      'Production impact: CNC Cell 7 at risk in 18 minutes',
      'Coolant system check: Flow rate nominal — bearing failure',
      'Autonomous slowdown: Speed reduced 35% to extend window',
      'Operator alert: 18-minute countdown + recommended action',
      'Maintenance dispatched: Bearing kit en route from crib',
      'Quality hold: 47 parts flagged for re-inspection',
    ],
    outcome: 'Machine saved. Controlled intervention. No scrap.',
    severity: 'critical',
    icon: '🌡',
  },
];

// Per-scene, per-stakeholder lens content — used by StakeholderLens component
export const sceneLens: Record<number, Partial<Record<string, { icon: string; insight: string; action: string }>>> = {
  1: {
    CIO: { icon: '💼', insight: '847 unknown OT assets are unmanaged operational liabilities. Every AI investment fails without this foundation.', action: 'Quantify your risk exposure' },
    CISO: { icon: '🛡', insight: 'Each unmanaged OT endpoint is an undetected lateral movement vector. You cannot defend what you cannot see.', action: 'Map your attack surface' },
    OTArchitect: { icon: '🏗', insight: '31 unsupported protocols are violating IEC 62443 zone boundaries. Shadow OT breaks your architectural integrity.', action: 'Audit zone compliance' },
    PlantManager: { icon: '🏭', insight: '8 dark operational zones are producing zero-confidence telemetry. Production decisions are being made blind.', action: 'Illuminate your floor' },
    ManufacturingIT: { icon: '🔌', insight: 'Stale CMDB means every IT/OT integration is built on fiction. Real-time asset sync is the fix.', action: 'Sync your CMDB' },
    ReliabilityEngineer: { icon: '🔧', insight: 'Unknown devices cannot be maintained. Fragmentation makes predictive maintenance statistically meaningless.', action: 'Start with asset truth' },
    SustainabilityOfficer: { icon: '🌱', insight: 'You cannot measure what you cannot see. Carbon twin accuracy depends on full asset coverage.', action: 'Establish energy baseline' },
    CTO: { icon: '⚙', insight: 'No API, pipeline, or AI model can serve data from assets you don\'t know exist. Visibility is your data foundation.', action: 'Design from truth' },
    OperationsLead: { icon: '📊', insight: '8 dark zones mean operations decisions are made without full situational awareness — every shift.', action: 'Recover operational sight' },
    PlatformEngineeringLead: { icon: '🚀', insight: 'Platform services cannot be deployed to unknown infrastructure. Visibility is your deployment prerequisite.', action: 'Build on known ground' },
  },
  2: {
    CIO: { icon: '💼', insight: '94% asset visibility means 94% of operational risk is now managed and insurable. Each percentage point has a dollar value.', action: 'Calculate ROI of visibility' },
    CISO: { icon: '🛡', insight: 'Zero Trust starts at Level 0. Every device fingerprinted, every zone bounded, every protocol known and monitored.', action: 'Enable Zero Trust OT' },
    OTArchitect: { icon: '🏗', insight: 'IEC 62443 compliance at 99%. All Purdue levels covered. DMZ architecture enforced with real-time policy validation.', action: 'View architecture details' },
    PlantManager: { icon: '🏭', insight: '98% asset coverage means OEE calculations are finally based on operational truth, not floor estimates.', action: 'Activate production visibility' },
    ManufacturingIT: { icon: '🔌', insight: '150+ protocols normalized into a unified data fabric. Every integration now works from a single source of truth.', action: 'Explore protocol coverage' },
    ReliabilityEngineer: { icon: '🔧', insight: 'Drift detection at 100ms means configuration deviations are caught before they become failures.', action: 'Set up drift alerts' },
    SustainabilityOfficer: { icon: '🌱', insight: 'Full Purdue coverage means energy metering at every level — enabling precise Scope 1 and Scope 2 accounting.', action: 'Enable energy visibility' },
    CTO: { icon: '⚙', insight: 'Centralized OT monitoring creates the real-time operational data layer your AI pipelines need to function at scale.', action: 'Design data architecture' },
    OperationsLead: { icon: '📊', insight: 'Mean time to identify an asset anomaly drops from hours to 4 minutes — before it becomes a production incident.', action: 'Accelerate detection' },
    PlatformEngineeringLead: { icon: '🚀', insight: 'OT CMDB as a service: auto-populated, always current, API-accessible — the infrastructure registry your platform needs.', action: 'Integrate with CMDB API' },
  },
  3: {
    CIO: { icon: '💼', insight: 'The operational knowledge graph creates the semantic layer that makes AI queries on your factory actually meaningful.', action: 'Explore enterprise graph' },
    CISO: { icon: '🛡', insight: 'Click any asset to see its vulnerability profile, dependency chain, and blast radius — all in real time.', action: 'Audit asset dependencies' },
    OTArchitect: { icon: '🏗', insight: 'Unified Namespace + Asset Administration Shell: every asset has a digital identity, every relationship is queryable.', action: 'Design your UNS topology' },
    PlantManager: { icon: '🏭', insight: 'Clicking a motor reveals its dependencies, maintenance history, and energy consumption — in one view.', action: 'Explore asset context' },
    ReliabilityEngineer: { icon: '🔧', insight: 'Operational lineage: trace any failure back through its dependency graph to find the true root cause.', action: 'Trace failure lineage' },
    SustainabilityOfficer: { icon: '🌱', insight: 'Energy consumption is contextualized at every node — from motor to line to facility to enterprise.', action: 'Map energy flows' },
  },
  4: {
    CIO: { icon: '💼', insight: 'A digital twin that grew from operational truth — not a CAD file — makes business-impacting simulations possible.', action: 'View twin ROI model' },
    OTArchitect: { icon: '🏗', insight: 'Sensor → Edge → Cloud → Decision → Outcome: the reference architecture for every industrial AI use case.', action: 'Download architecture' },
    ReliabilityEngineer: { icon: '🔧', insight: 'Asset twin behavioral models detect failure signatures 4–6 hours before physical breakdown.', action: 'Activate PdM twin' },
    SustainabilityOfficer: { icon: '🌱', insight: 'Carbon Twin simulates emissions impact of production decisions before they are executed.', action: 'Configure carbon twin' },
    PlantManager: { icon: '🏭', insight: 'Factory twin runs what-if scenarios — change schedules, shift patterns, or maintenance windows without touching the floor.', action: 'Run factory simulation' },
  },
  5: {
    CIO: { icon: '💼', insight: 'Autonomous operations eliminate reactive decision cycles. MTTR drops from hours to minutes with zero operator intervention.', action: 'Review incident ROI' },
    CISO: { icon: '🛡', insight: 'Unauthorized device detection + network isolation in under 90ms — before lateral movement occurs.', action: 'Test threat response' },
    PlantManager: { icon: '🏭', insight: 'The factory responds to anomalies faster than any shift supervisor — correlating topology, telemetry, and history.', action: 'Configure alert thresholds' },
    ReliabilityEngineer: { icon: '🔧', insight: 'Autonomous maintenance scheduling selects optimal windows based on production plan, parts availability, and risk score.', action: 'Set up autonomous maintenance' },
    OperationsLead: { icon: '📊', insight: 'Every autonomous action is logged with full context — why it happened, what it changed, what was avoided.', action: 'Review action log' },
  },
};

export const storyScenes = [
  { id: 'hero',     label: 'Start Here',               icon: '🏠', short: 'Intro'    },
  { id: 'scene1',  label: 'The Invisible Factory',     icon: '🌑', short: 'Problem'  },
  { id: 'scene2',  label: 'OT Visibility',             icon: '👁',  short: 'Visibility'},
  { id: 'scene3',  label: 'Operational Graph',         icon: '🔗', short: 'Context'  },
  { id: 'scene4',  label: 'Digital Twin',              icon: '🧬', short: 'Twin'     },
  { id: 'scene5',      label: 'Autonomous Ops',            icon: '⚡', short: 'Autonomy' },
  { id: 'bigpicture',  label: 'Ecosystem Map',             icon: '🗺', short: 'Map'      },
  { id: 'fof',         label: 'Factory of the Future',     icon: '🏭', short: 'FoF'      },
  { id: 'target',  label: 'Target State Blueprint',    icon: '🎯', short: 'Target'   },
  { id: 'scene6',  label: 'OT Services',               icon: '📦', short: 'Services' },
  { id: 'scene7',  label: 'Global Governance',         icon: '🌍', short: 'Govern'   },
  { id: 'roadmap', label: 'Transformation Roadmap',    icon: '🗺', short: 'Roadmap'  },
  { id: 'deloitte',label: 'Deloitte Partnership',      icon: '🤝', short: 'Deloitte' },
  { id: 'scene8',  label: 'Use Case Studio',           icon: '🎨', short: 'Use Cases'},
  { id: 'cio',     label: 'Command Center',            icon: '🚀', short: 'Cockpit'  },
];

export const globalKPIs = {
  totalAssets: 25780,
  managedAssets: 24241,
  visibilityScore: 94,
  activeIncidents: 18,
  avgCompliance: 81,
  activeTwins: 58,
  deployedServices: 127,
  mttrMinutes: 47,
};

// ─── Factory of the Future ────────────────────────────────────────────────────

export const fofUseCases = [
  {
    id: 'digital-twin',
    number: 1,
    icon: '🧬',
    title: 'Digital Twins',
    tagline: 'The living operational mirror — not a 3D model',
    description: 'Asset visibility provides the continuous data feed that makes digital twins alive and accurate. Without knowing what assets exist, how they connect, and their real-time state, a twin is a static model that decays from day one.',
    visibilityGate: '95%+ asset coverage + protocol normalization + topology mapping',
    businessValue: '$4.2M / yr',
    businessDetail: 'per facility via avoided failures and predictive operations',
    operationalValue: '67% less unplanned downtime',
    efficiency: '+34% OEE improvement',
    secondOrder: ['Supply chain simulation capability', 'Regulatory digital thread', 'Foundation for autonomous ops'],
    proof: { org: 'Global Biologics Manufacturer', result: '140 asset twins across 6 plants · 43% fewer equipment failures · 18 months' },
    color: '#005EB8', bg: '#EAF4FF',
  },
  {
    id: 'predictive-maint',
    number: 2,
    icon: '🔮',
    title: 'Predictive Maintenance',
    tagline: 'Fix before it fails — zero production surprises',
    description: 'Real-time asset telemetry feeds ML failure models that predict equipment degradation days before breakdown. Maintenance becomes a planned activity, not an emergency scramble that halts production.',
    visibilityGate: 'Sensor-level telemetry from all critical assets with protocol-normalized time-series',
    businessValue: '$2.8M / yr',
    businessDetail: 'per plant in avoided downtime and emergency-maintenance labour',
    operationalValue: '35% fewer unplanned stops',
    efficiency: '−42% maintenance cost',
    secondOrder: ['Extended asset lifetimes', 'Spare-parts inventory reduction', 'Shift to outcome-based contracts'],
    proof: { org: 'Top-5 Pharma Contract Manufacturer', result: '47 assets under PdM · MTTR 8 h → 45 min · 12 months' },
    color: '#00A3E0', bg: '#E0F4FF',
  },
  {
    id: 'carbon-twin',
    number: 3,
    icon: '♻',
    title: 'Carbon & Energy Twin',
    tagline: 'Scope 1/2 emissions tracked, modelled, and optimised in real time',
    description: 'A carbon twin requires knowing exactly where energy flows through every asset, process, and utility. Visibility enables closed-loop carbon control that turns ESG commitments into an engineering problem you can solve.',
    visibilityGate: 'Energy metering at asset level + process-parameter correlation across L0–L3',
    businessValue: '€3.4M / yr',
    businessDetail: 'in energy savings + carbon credit value at full deployment',
    operationalValue: '22% Scope 1 reduction',
    efficiency: '−18% energy intensity / unit',
    secondOrder: ['EU Taxonomy alignment', 'Scope 3 supplier data chain', 'Green premium pricing capability'],
    proof: { org: 'European Specialty Chemical Producer', result: '28% Scope 1 reduction · first verified carbon credits sold · 14 months' },
    color: '#12B3A8', bg: '#E6FAF8',
  },
  {
    id: 'ai-quality',
    number: 4,
    icon: '🔬',
    title: 'AI Quality Inspection',
    tagline: 'Zero defects at line speed — full traceability to root cause',
    description: 'Computer vision + process-parameter correlation catches defects the moment they form. Asset visibility provides the process context that turns a detection signal into a root-cause-linked intervention — critical in GxP-regulated manufacturing.',
    visibilityGate: 'Machine-level process params + vision inference layer + OT operational-graph context',
    businessValue: '$5.1M / yr',
    businessDetail: 'in scrap, rework, and customer-return cost avoidance',
    operationalValue: '73% fewer defect escapes',
    efficiency: '−61% scrap rate',
    secondOrder: ['GxP-ready quality digital thread', 'Batch release acceleration', 'Customer audit readiness on demand'],
    proof: { org: 'Life Sciences Equipment Manufacturer', result: 'AI inspection on 3 assembly lines · 81% reduction in customer returns · 9 months' },
    color: '#F5A623', bg: '#FFFBEB',
  },
  {
    id: 'autonomous-ops',
    number: 5,
    icon: '⚡',
    title: 'Autonomous Operations',
    tagline: 'The factory that responds, adapts, and self-heals without operator intervention',
    description: 'Autonomous operations is the convergence of visibility, context, twins, and intelligence. Every automated decision is only trustworthy if it is grounded in accurate, real-time operational state. Visibility is the prerequisite for trust in automation.',
    visibilityGate: 'Full maturity stack — Visible → Contextual → Intelligent — all prerequisite capabilities active',
    businessValue: '$11.2M / yr',
    businessDetail: 'blended across downtime, quality, energy, and labour at full deployment',
    operationalValue: '92% events resolved autonomously',
    efficiency: 'Near-zero unplanned stops',
    secondOrder: ['Factory-as-a-Service model enablement', 'Workforce redeployment to higher-value tasks', 'Continuous regulatory compliance'],
    proof: { org: 'Tier-1 Automotive OEM Supplier', result: '94% autonomous event resolution · avg response 8 min vs 4 h benchmark · 24 months' },
    color: '#6366F1', bg: '#F0F0FF',
  },
];

export const marketProofPoints = [
  {
    icon: '💊',
    sector: 'Pharma & Life Sciences',
    company: 'Global Top-10 Pharmaceutical Manufacturer',
    headline: '94% OT asset visibility in 8 months',
    metrics: ['$4.2M annual savings', '67% MTTR reduction', '23 critical vulnerabilities resolved'],
    quote: 'We could not activate a single digital twin until we knew what we had. Visibility was the unlock.',
  },
  {
    icon: '🏭',
    sector: 'Industrial Equipment',
    company: 'European Life Sciences Equipment Producer',
    headline: 'Autonomous quality inspection across 3 lines',
    metrics: ['81% reduction in customer returns', 'GxP audit pack in <2 hours', '9-month implementation'],
    quote: 'Our FDA audit preparation time dropped from 3 weeks to 2 hours once every asset and process was digitally traceable.',
  },
  {
    icon: '⚗',
    sector: 'Specialty Chemicals',
    company: 'Mid-size European Chemical Manufacturer',
    headline: '28% Scope 1 emissions reduction via carbon twin',
    metrics: ['€3.4M/yr energy savings', 'First carbon credits sold in month 14', '4-plant rollout in 18 months'],
    quote: 'The carbon twin turned sustainability from a reporting obligation into an operational lever we actively manage every shift.',
  },
];

// ─── Target State Blueprint ───────────────────────────────────────────────────

export const targetStateKPIs = [
  { metric: 'OT Asset Visibility',      current: '~35–45%',      target: '≥ 98%',                 months: 6,  color: '#005EB8', icon: '👁'  },
  { metric: 'Unplanned Downtime',        current: 'Baseline',     target: '−65%',                  months: 18, color: '#00A3E0', icon: '⏱'  },
  { metric: 'Active Digital Twins',      current: '0',            target: '80+',                   months: 24, color: '#12B3A8', icon: '🧬' },
  { metric: 'Scope 1 Emissions',         current: 'Baseline',     target: '−28%',                  months: 30, color: '#10B981', icon: '♻'  },
  { metric: 'Mean Time to Repair',       current: 'Baseline',     target: '−55%',                  months: 18, color: '#F5A623', icon: '🔧' },
  { metric: 'OT Security Compliance',   current: '~50%',         target: 'IEC 62443 Level 3',     months: 12, color: '#D64545', icon: '🛡'  },
  { metric: 'Batch Release Cycle',       current: 'Baseline',     target: '−30%',                  months: 24, color: '#6366F1', icon: '📋' },
  { metric: 'GxP Audit Readiness',       current: 'Manual / weeks', target: 'Continuous / 2 hours', months: 18, color: '#003B73', icon: '✅' },
];

export const peerBenchmarks = [
  { org: 'Sartorius Today (est.)',        maturity: 'Fragmented → Visible', visibility: 40, twins: 0,  autonomy: 5,  color: '#D64545' },
  { org: 'Industry Average (Life Sci.)', maturity: 'Visible',               visibility: 58, twins: 8,  autonomy: 15, color: '#F5A623' },
  { org: 'Industry Leaders (Top 25%)',   maturity: 'Contextual',            visibility: 81, twins: 34, autonomy: 38, color: '#00A3E0' },
  { org: 'Best-in-Class (Top 5%)',       maturity: 'Intelligent',           visibility: 96, twins: 80, autonomy: 71, color: '#12B3A8' },
  { org: 'Sartorius Target (36 months)', maturity: 'Intelligent → Autonomous', visibility: 98, twins: 80, autonomy: 80, color: '#005EB8' },
];

export const lifeSciencesCapabilities = [
  { icon: '📋', title: 'FDA 21 CFR Part 11', desc: 'Electronic records and audit trail for every automated action and system change' },
  { icon: '🧪', title: 'GxP Digital Thread', desc: 'End-to-end data integrity from raw material receipt to batch release — fully traceable' },
  { icon: '🏭', title: 'Cleanroom OT Visibility', desc: 'Passive asset discovery with zero cleanroom contamination risk — qualified approach' },
  { icon: '📦', title: 'Batch Process Twin', desc: 'Digital twin for bioprocess fermentation with parameter-to-quality correlation' },
  { icon: '🔬', title: 'PAT Integration', desc: 'Process Analytical Technology data feeds into quality twin for real-time release decisions' },
  { icon: '📄', title: 'Annex 11 Compliance', desc: 'EU GMP computerised systems validation built into the platform from day one' },
];

// ─── Transformation Roadmap ───────────────────────────────────────────────────

export const roadmapPhases = [
  {
    id: 'foundation',
    number: 1,
    title: 'Foundation',
    subtitle: 'See Everything',
    duration: '0 – 6 Months',
    color: '#F5A623',
    bg: '#FFFBEB',
    icon: '👁',
    summary: 'Establish the operational truth layer. Every asset discovered, mapped, and governed before a single twin is activated.',
    milestones: [
      { week: 4,  label: 'OT Asset Discovery',      detail: 'Passive scan across all Purdue levels — 95%+ asset fingerprinting with zero production impact' },
      { week: 8,  label: 'Network Topology Map',    detail: 'IT/OT boundary defined, DMZ architecture validated, IEC 62443 zone segmentation confirmed' },
      { week: 12, label: 'CMDB Populated',           detail: 'All assets in the asset management system with lifecycle status, compliance state, and GxP flags' },
      { week: 16, label: 'OT Security Baseline',    detail: 'IEC 62443 gap assessment complete, remediation plan approved and resourced' },
      { week: 20, label: 'Data Connectivity Layer', detail: 'Protocol normalisation active — OPC-UA, Modbus, HART, S7, EtherNet/IP all flowing into unified data fabric' },
      { week: 24, label: 'Phase Gate ✓',            detail: '98% asset coverage verified · security baseline met · data quality score >90% · GxP inventory confirmed' },
    ],
    quickWins: [
      { day: 30, win: '800+ unknown devices identified and classified — operational risk quantified for the first time' },
      { day: 60, win: 'OT/IT firewall rule validation complete — critical rule conflicts resolved, compliance gaps closed' },
      { day: 90, win: 'First live compliance dashboard — IEC 62443 and GxP coverage visible in real time to stakeholders' },
    ],
    prerequisites: [
      'Network access approval for passive scanning (zero production impact)',
      'IT/OT firewall change process agreed with CISO and operations',
      'CMDB / ITSM system identified and API access granted',
      'GxP inventory scope agreed with QA and regulatory affairs',
    ],
    integrations: ['ServiceNow / existing CMDB', 'Active Directory', 'Network management system (NMS)'],
    deliverables: ['Complete OT Asset Inventory', 'Network topology diagram', 'IEC 62443 gap report', 'GxP-flagged asset register'],
  },
  {
    id: 'intelligence',
    number: 2,
    title: 'Intelligence',
    subtitle: 'Understand Everything',
    duration: '6 – 18 Months',
    color: '#005EB8',
    bg: '#EAF4FF',
    icon: '🧠',
    summary: 'Activate digital twins, build the operational knowledge graph, and deploy predictive intelligence across critical asset classes.',
    milestones: [
      { week: 28, label: 'Operational Knowledge Graph', detail: 'Semantic relationships between assets, processes, quality parameters, and maintenance records' },
      { week: 32, label: 'First 20 Digital Twins',       detail: 'Critical production equipment with live telemetry feeds and established behavioural baselines' },
      { week: 40, label: 'Predictive Maintenance Live',  detail: 'ML failure models deployed for top-10 critical assets ranked by downtime impact' },
      { week: 48, label: 'Carbon & Energy Twin',          detail: 'Scope 1/2 emissions tracked in real time at asset and process level across all plants' },
      { week: 56, label: 'AI Quality Inspection',         detail: '3 assembly lines with computer vision + process-parameter correlation — GxP-validated approach' },
      { week: 72, label: 'Phase Gate ✓',                  detail: '80 twins active · PdM accuracy >85% · carbon baseline established · GxP audit trail confirmed' },
    ],
    quickWins: [
      { day: 210, win: 'First predictive alert prevents unplanned shutdown — $180K saving documented and communicated to leadership' },
      { day: 240, win: 'Carbon twin identifies 3 optimisation opportunities — €420K annual saving quantified and approved for implementation' },
      { day: 270, win: 'AI quality system catches defect class previously discovered only at end-of-line customer inspection' },
    ],
    prerequisites: [
      'Phase 1 complete — 95%+ asset coverage and data connectivity layer operational',
      'Cloud analytics environment provisioned (AWS IoT SiteWise / TwinMaker)',
      'GxP data governance framework and 21 CFR Part 11 validation approach approved',
      'ML model validation process agreed with quality assurance',
    ],
    integrations: ['SAP S/4HANA (ERP)', 'OSIsoft PI / AVEVA Historian', 'SAP PM / Maximo (EAM)', 'LIMS', 'MES'],
    deliverables: ['80 digital twins', 'PdM on top-10 assets', 'Carbon twin baseline', 'AI quality on 3 lines', 'GxP audit trail live'],
  },
  {
    id: 'autonomy',
    number: 3,
    title: 'Autonomy',
    subtitle: 'Operate Everything',
    duration: '18 – 36 Months',
    color: '#12B3A8',
    bg: '#E6FAF8',
    icon: '⚡',
    summary: 'Deploy autonomous orchestration, self-healing operations, and continuous GxP compliance monitoring across the full Sartorius plant network.',
    milestones: [
      { week: 80,  label: 'Autonomous Event Response',  detail: '85%+ of operational events resolved without human intervention — validated governance framework active' },
      { week: 88,  label: 'Digital Product Passport',   detail: 'End-to-end product lifecycle traceability from raw material to customer delivery — EU DPP compliant' },
      { week: 96,  label: 'Factory Copilot Deployed',   detail: 'LLM-powered conversational interface over the full operational graph for every role and shift' },
      { week: 104, label: 'Worker Safety Twin',          detail: 'Real-time ergonomic risk and environmental exposure monitoring across all production zones' },
      { week: 120, label: 'Multi-Site Rollout',          detail: 'Full platform scaled to all Sartorius facilities globally under unified governance and policy enforcement' },
      { week: 144, label: 'Target State Validated ✓',   detail: 'All KPI targets met · continuous improvement loop active · GxP audit continuous · IEC 62443 Level 3 maintained' },
    ],
    quickWins: [
      { day: 570, win: 'First autonomous batch parameter adjustment executed — validated and signed off by QA, zero manual intervention required' },
      { day: 600, win: 'Regulatory inspection readiness on demand — full audit pack generated in <2 hours vs 3 weeks previously' },
      { day: 630, win: 'Multi-site OT governance live — policy drift detected and auto-remediated across 4 facilities simultaneously' },
    ],
    prerequisites: [
      'Phase 2 complete — 80 twins active, PdM and quality systems live',
      'Autonomous action governance framework approved by board and quality',
      'GxP validation of automated decision workflows (IQ/OQ/PQ completed)',
      'Change management and workforce upskilling programme completed',
    ],
    integrations: ['Supply chain / supplier portal', 'Regulatory submission systems', 'Customer quality portal', 'CDP / GHG Protocol carbon reporting'],
    deliverables: ['Autonomous operations platform', 'DPP implementation', 'Multi-site global governance', 'GxP continuous compliance system'],
  },
];

// ─── Deloitte Partnership ─────────────────────────────────────────────────────

export const deloitteData = {
  tagline: 'Your transformation partner from strategy to autonomous operations',
  description: 'Deloitte combines OT/ICS engineering, life sciences manufacturing expertise, cybersecurity, and enterprise technology in one integrated team. We have delivered OT transformation for 200+ manufacturing clients globally — including pharma, biotech, and life sciences equipment manufacturers with the same GxP, FDA, and IEC 62443 requirements as Sartorius.',

  phaseServices: [
    {
      phase: 'Foundation (0–6 months)',
      color: '#F5A623',
      icon: '👁',
      services: [
        { name: 'OT Maturity Assessment',      icon: '📊', desc: 'Benchmarked assessment of current OT state against life sciences industry peers with quantified gap analysis', duration: '4 weeks' },
        { name: 'Target Architecture Design',  icon: '🏗',  desc: 'Sartorius-specific reference architecture with GxP compliance, IEC 62443 zoning, and cloud connectivity built in', duration: '6 weeks' },
        { name: 'OT Security Assessment',      icon: '🛡',  desc: 'IEC 62443 gap analysis, network segmentation review, zero-trust OT access roadmap', duration: '6 weeks' },
        { name: 'Asset Discovery & CMDB',      icon: '🔍', desc: 'Deployment and tuning of passive OT discovery with GxP inventory qualification across all facilities', duration: '8 weeks' },
      ],
    },
    {
      phase: 'Intelligence (6–18 months)',
      color: '#005EB8',
      icon: '🧠',
      services: [
        { name: 'Digital Twin Activation',    icon: '🧬', desc: 'Twin modelling, data pipeline build, behavioural baseline — using our Twin Activate™ accelerator', duration: '12 weeks' },
        { name: 'Predictive Maintenance',     icon: '🔮', desc: 'ML model development, sensor integration, alert workflow — pre-validated for GxP environments', duration: '10 weeks' },
        { name: 'GxP Digital Thread',          icon: '📋', desc: 'FDA 21 CFR Part 11 compliant data governance, electronic batch records, and full audit-trail framework', duration: '8 weeks' },
        { name: 'Carbon & Sustainability Twin',icon: '♻',  desc: 'Scope 1/2/3 measurement framework with closed-loop optimisation using our Carbon Lens™ platform', duration: '10 weeks' },
      ],
    },
    {
      phase: 'Autonomy (18–36 months)',
      color: '#12B3A8',
      icon: '⚡',
      services: [
        { name: 'Autonomous Ops Platform',    icon: '⚡', desc: 'Orchestration, self-healing workflows, and human-in-loop governance framework with GxP sign-off', duration: '16 weeks' },
        { name: 'Factory Copilot Deploy',      icon: '🤖', desc: 'LLM over the operational graph — natural-language factory intelligence, compliant with data privacy requirements', duration: '8 weeks' },
        { name: 'Global Platform Governance', icon: '🌐', desc: 'Multi-site rollout, StackSets deployment, global policy enforcement with drift detection', duration: '20 weeks' },
        { name: 'Operate & Optimise',         icon: '📈', desc: 'Managed operations, continuous model improvement, KPI measurement, and quarterly value reviews', duration: 'Ongoing' },
      ],
    },
  ],

  differentiators: [
    { icon: '🔩', title: 'OT + IT + Strategy. One Team.', desc: 'No handoffs between OT engineering, cyber, cloud architecture, and business strategy. One integrated Deloitte team owns the full transformation journey.' },
    { icon: '💊', title: 'Life Sciences Manufacturing Depth', desc: 'Dedicated GxP, FDA 21 CFR Part 11, and EudraLex Annex 11 expertise. We have completed OT transformations in pharma, biotech, and life sciences equipment manufacturing with the same compliance profile as Sartorius.' },
    { icon: '⚡', title: 'Proven Accelerators Cut Time to Value', desc: 'OT Clarity™ for asset discovery, Twin Activate™ for digital twin deployment, GxP DataGuard™ for data governance, and Carbon Lens™ for sustainability — pre-built and pre-validated to cut delivery time by 40%.' },
    { icon: '🌍', title: 'Global Scale, Local Delivery', desc: 'Deloitte practitioners in 50+ countries including all major Sartorius manufacturing locations. Global architecture, local implementation expertise, no travel risk on delivery.' },
  ],

  accelerators: [
    { name: 'OT Clarity™',      icon: '🔍', desc: 'Asset discovery and visualisation accelerator — deployed and delivering insights in under 2 weeks, zero production impact' },
    { name: 'Twin Activate™',   icon: '🧬', desc: 'Digital twin activation framework with 40+ pre-built asset twin templates for pharma, biotech, and process manufacturing' },
    { name: 'GxP DataGuard™',  icon: '📋', desc: 'FDA 21 CFR Part 11 / Annex 11 compliant data governance and audit trail framework — pre-validated for life sciences' },
    { name: 'Carbon Lens™',     icon: '♻',  desc: 'Scope 1/2/3 measurement and closed-loop carbon twin platform with EU Taxonomy and CDP reporting integration' },
  ],
};
