import type { ServiceCard, UseCase, OTNode, PlantSite, KPI } from '../types';

export const stakeholderProfiles = {
  CIO: {
    headline: 'From Operational Fragmentation to Industrial Intelligence',
    subhead: 'Build a governed digital platform from the factory floor up - one that improves as it grows.',
    kpis: ['Operational Cost Reduction', 'MTTR Improvement', 'Deployment Velocity', 'OT Coverage'],
    focus: 'Business value and governance at enterprise scale',
  },
  CTO: {
    headline: 'The Architecture of Autonomous Industrial Systems',
    subhead: 'Build the technical foundation that makes AI-driven operations possible.',
    kpis: ['API Availability', 'Data Pipeline Latency', 'Twin Fidelity', 'Platform Adoption'],
    focus: 'Technical architecture and platform capability',
  },
  PlantManager: {
    headline: 'Every Asset. Every Signal. Every Decision - In Context.',
    subhead: 'Your factory operates with accurate, real-time awareness of every asset, process, and event.',
    kpis: ['OEE Improvement', 'Unplanned Downtime', 'Energy Per Unit', 'Quality Defect Rate'],
    focus: 'Operational efficiency and production reliability',
  },
  ManufacturingIT: {
    headline: 'OT/IT Convergence Without Compromise',
    subhead: 'Connect industrial systems to digital infrastructure without sacrificing operational stability.',
    kpis: ['IT/OT Integration Points', 'Protocol Coverage', 'Segmentation Health', 'Patch Compliance'],
    focus: 'Integration, security, and operational continuity',
  },
  OTArchitect: {
    headline: 'Purdue-Compliant. Zero Trust. Digitally Native.',
    subhead: 'Design industrial architectures that are observable, governed, and intelligently orchestrated.',
    kpis: ['Zone Compliance', 'DMZ Coverage', 'Protocol Normalization', 'Asset Fingerprint Rate'],
    focus: 'Architecture design, zoning, and standards compliance',
  },
  CISO: {
    headline: 'OT Security Posture Built from Operational Truth',
    subhead: 'Visibility is not optional. Every unknown asset is an unmanaged risk.',
    kpis: ['Unknown Assets', 'Vulnerability Exposure', 'Segmentation Violations', 'Mean Time to Detect'],
    focus: 'Security posture, threat surface, and compliance',
  },
  ReliabilityEngineer: {
    headline: 'Predict. Prevent. Perform.',
    subhead: 'Digital twins that evolve from real operational behavior enable proactive reliability.',
    kpis: ['MTBF Improvement', 'PdM Accuracy', 'False Alarm Rate', 'Maintenance Cost Reduction'],
    focus: 'Asset reliability, predictive maintenance, and failure analysis',
  },
  SustainabilityOfficer: {
    headline: 'Industrial Sustainability Starts with Operational Visibility',
    subhead: 'Carbon optimization requires knowing exactly where energy flows in your factory.',
    kpis: ['Carbon Reduction', 'Energy Intensity', 'Renewable Integration', 'Scope 2 Emissions'],
    focus: 'Energy optimization, carbon reduction, and ESG reporting',
  },
  OperationsLead: {
    headline: 'Operations That Think, Adapt, and Self-Optimize',
    subhead: 'When your factory has operational intelligence, every decision is informed by real context.',
    kpis: ['Throughput Increase', 'Shift Efficiency', 'Incident Response Time', 'Worker Productivity'],
    focus: 'Operational performance and workforce augmentation',
  },
  PlatformEngineeringLead: {
    headline: 'Build Once. Deploy Everywhere. Govern Continuously.',
    subhead: 'A reusable OT platform foundation that accelerates every use case you deliver.',
    kpis: ['Service Deployment Time', 'Reuse Rate', 'Platform Coverage', 'Time to Value'],
    focus: 'Platform scalability, reusability, and developer experience',
  },
};

export const maturityJourney = [
  { id: 'Fragmented', label: 'Fragmented', desc: 'Unknown assets, disconnected systems, zero visibility', color: '#D64545', icon: 'help-circle' },
  { id: 'Visible', label: 'Visible', desc: 'Asset discovery, topology mapping, protocol awareness', color: '#F5A623', icon: 'eye' },
  { id: 'Contextual', label: 'Contextual', desc: 'Semantic relationships, operational knowledge graph', color: '#00A3E0', icon: 'network' },
  { id: 'Intelligent', label: 'Intelligent', desc: 'Digital twins, AI-assisted operations, predictive insights', color: '#005EB8', icon: 'cpu' },
  { id: 'Autonomous', label: 'Autonomous', desc: 'Self-healing systems, autonomous orchestration, zero-touch', color: '#12B3A8', icon: 'bot' },
];

// Purdue levels: L4 Enterprise at TOP (low y%), L0 Field at BOTTOM (high y%)
// L4 ~8%, L3 ~25%, DMZ ~42%, L2 ~58%, L1 ~74%, L0 ~90%
export const otNodes: OTNode[] = [
  { id: 'cloud1', label: 'Azure IoT Hub', type: 'Cloud', status: 'online', zone: 'Level4', x: 50, y: 8, protocol: 'MQTT/TLS' },
  { id: 'hist1', label: 'OSIsoft PI', type: 'Server', status: 'online', zone: 'Level3', x: 30, y: 25, vendor: 'OSIsoft', protocol: 'PI API' },
  { id: 'mes1', label: 'MES Platform', type: 'Server', status: 'online', zone: 'Level3', x: 65, y: 25, vendor: 'SAP ME', protocol: 'REST' },
  { id: 'net1', label: 'OT Firewall', type: 'Network', status: 'online', zone: 'DMZ', x: 50, y: 42, vendor: 'Fortinet' },
  { id: 'hmi1', label: 'HMI Station A', type: 'HMI', status: 'online', zone: 'Level2', x: 18, y: 58, vendor: 'Wonderware', protocol: 'OPC-DA' },
  { id: 'hmi2', label: 'HMI Station B', type: 'HMI', status: 'offline', zone: 'Level2', x: 48, y: 58, vendor: 'Ignition', protocol: 'OPC-UA' },
  { id: 'plc1', label: 'PLC Line 1', type: 'PLC', status: 'online', zone: 'Level1', x: 18, y: 74, vendor: 'Siemens', protocol: 'S7', firmware: '2.8.1' },
  { id: 'plc2', label: 'PLC Line 2', type: 'PLC', status: 'warning', zone: 'Level1', x: 50, y: 74, vendor: 'Rockwell', protocol: 'EtherNet/IP', firmware: '1.4.0' },
  { id: 'plc3', label: 'PLC Utilities', type: 'PLC', status: 'critical', zone: 'Level1', x: 80, y: 74, vendor: 'ABB', protocol: 'Modbus', firmware: '0.9.2', vulnerabilities: 3 },
  { id: 'sensor1', label: 'Vibration Array', type: 'Sensor', status: 'online', zone: 'Level0', x: 10, y: 90, protocol: 'IO-Link' },
  { id: 'sensor2', label: 'Thermal Sensor', type: 'Sensor', status: 'warning', zone: 'Level0', x: 33, y: 90, protocol: 'HART' },
  { id: 'sensor3', label: 'Flow Meter', type: 'Sensor', status: 'unknown', zone: 'Level0', x: 60, y: 90, protocol: 'Modbus RTU' },
  { id: 'sensor4', label: 'Pressure Grid', type: 'Sensor', status: 'online', zone: 'Level0', x: 82, y: 90, protocol: 'IO-Link' },
];

export const serviceCards: ServiceCard[] = [
  { id: 'connectivity', name: 'OT Connectivity Hub', category: 'Connectivity', description: 'Unified protocol translation - Modbus, OPC-UA, MQTT, EtherNet/IP, S7, HART bridged into a normalized data fabric.', icon: 'network', kpiImpact: ['Protocol Coverage', 'Data Latency', 'Integration Cost'], maturityRequired: 'Visible', deploymentComplexity: 'Medium', edgeSplit: 70, cloudSplit: 30, twinIntegration: true },
  { id: 'ot-security', name: 'OT Security Posture', category: 'Security', description: 'IEC 62443 compliant segmentation, passive deep-packet inspection, Zero Trust network access for OT environments.', icon: 'shield', kpiImpact: ['Unknown Assets', 'Vulnerability Exposure', 'Compliance Score'], maturityRequired: 'Visible', deploymentComplexity: 'High', edgeSplit: 60, cloudSplit: 40, twinIntegration: false },
  { id: 'asset-mgmt', name: 'OT Asset Management', category: 'Asset Visibility', description: 'Auto-discovery, fingerprinting, CMDB population, firmware tracking, and lifecycle governance for every OT asset.', icon: 'search', kpiImpact: ['Asset Coverage', 'Firmware Compliance', 'MTTR'], maturityRequired: 'Visible', deploymentComplexity: 'Low', edgeSplit: 40, cloudSplit: 60, twinIntegration: true },
  { id: 'backup-recovery', name: 'OT Backup & Recovery', category: 'Backup & Recovery', description: 'Automated PLC/HMI configuration backup, version control, rapid restore for operational continuity.', icon: 'database', kpiImpact: ['RTO', 'Config Compliance', 'Recovery Success Rate'], maturityRequired: 'Visible', deploymentComplexity: 'Low', edgeSplit: 50, cloudSplit: 50, twinIntegration: false },
  { id: 'pam', name: 'OT Privileged Access', category: 'PAM', description: 'Vendor-agnostic privileged access management with session recording, just-in-time access, and full audit trails.', icon: 'lock', kpiImpact: ['Unauthorized Access', 'Audit Coverage', 'Vendor Risk'], maturityRequired: 'Visible', deploymentComplexity: 'Medium', edgeSplit: 20, cloudSplit: 80, twinIntegration: false },
  { id: 'ot-ad', name: 'OT Active Directory', category: 'OT Active Directory', description: 'Industrial identity services designed for OT - role-based access, machine identity, operational zones, workforce provisioning.', icon: 'users', kpiImpact: ['Identity Coverage', 'Zone Compliance', 'Provisioning Time'], maturityRequired: 'Contextual', deploymentComplexity: 'High', edgeSplit: 30, cloudSplit: 70, twinIntegration: false },
  { id: 'monitoring', name: 'Centralized OT Monitoring', category: 'Monitoring', description: 'Real-time telemetry aggregation from all levels - Purdue L0-L4, anomaly detection, operational alerting.', icon: 'activity', kpiImpact: ['MTTD', 'Alert Accuracy', 'Coverage Ratio'], maturityRequired: 'Visible', deploymentComplexity: 'Medium', edgeSplit: 40, cloudSplit: 60, twinIntegration: true },
  { id: 'patch-mgmt', name: 'OT Patch Management', category: 'Patch Management', description: 'Risk-aware patch scheduling that respects operational windows, validates firmware integrity, and maintains uptime.', icon: 'clock', kpiImpact: ['Patch Compliance', 'CVE Exposure', 'Maintenance Cost'], maturityRequired: 'Contextual', deploymentComplexity: 'High', edgeSplit: 30, cloudSplit: 70, twinIntegration: false },
  { id: 'remote-access', name: 'Secure Remote Access', category: 'Remote Access', description: 'Zero Trust remote access for OT with session recording, conditional access, and vendor isolation.', icon: 'globe', kpiImpact: ['Vendor Incidents', 'Remote Efficiency', 'Compliance'], maturityRequired: 'Visible', deploymentComplexity: 'Medium', edgeSplit: 20, cloudSplit: 80, twinIntegration: false },
  { id: 'dpp', name: 'Digital Product Passport', category: 'DPP', description: 'Regulatory-grade digital product lifecycle tracking from raw material to end-of-life - EU DPP compliant.', icon: 'git-merge', kpiImpact: ['Regulatory Compliance', 'Supply Chain Visibility', 'Carbon Traceability'], maturityRequired: 'Intelligent', deploymentComplexity: 'High', edgeSplit: 10, cloudSplit: 90, twinIntegration: true },
  { id: 'sustainability', name: 'Sustainability Intelligence', category: 'Sustainability', description: 'Real-time Scope 1/2/3 emissions tracking, energy optimization, carbon twin simulation, ESG reporting.', icon: 'leaf', kpiImpact: ['Carbon Reduction', 'Energy Intensity', 'ESG Score'], maturityRequired: 'Intelligent', deploymentComplexity: 'Medium', edgeSplit: 30, cloudSplit: 70, twinIntegration: true },
  { id: 'predictive-maint', name: 'Predictive Maintenance', category: 'Predictive Maintenance', description: 'ML-based failure prediction using vibration, thermal, acoustic, and operational signatures at the asset level.', icon: 'wrench', kpiImpact: ['MTBF', 'Unplanned Downtime', 'Maintenance Cost'], maturityRequired: 'Intelligent', deploymentComplexity: 'Medium', edgeSplit: 50, cloudSplit: 50, twinIntegration: true },
  { id: 'ai-quality', name: 'AI Quality Inspection', category: 'AI Quality Inspection', description: 'Computer vision defect detection at line speed - zero sampling bias, full traceability, process correlation.', icon: 'scan', kpiImpact: ['Defect Rate', 'Scrap Cost', 'Customer Returns'], maturityRequired: 'Intelligent', deploymentComplexity: 'High', edgeSplit: 80, cloudSplit: 20, twinIntegration: true },
  { id: 'carbon-opt', name: 'Carbon Optimization Engine', category: 'Carbon Optimization', description: 'Closed-loop carbon control - real-time tracking, process optimization recommendations, offset intelligence.', icon: 'leaf', kpiImpact: ['Scope 1 Emissions', 'Energy Cost', 'Carbon Credits'], maturityRequired: 'Autonomous', deploymentComplexity: 'High', edgeSplit: 30, cloudSplit: 70, twinIntegration: true },
  { id: 'root-cause', name: 'Root Cause Intelligence', category: 'Root Cause Intelligence', description: 'AI-driven causal analysis across the operational graph - correlates topology, telemetry, and maintenance history.', icon: 'git-branch', kpiImpact: ['MTTR', 'Repeat Incidents', 'Investigation Cost'], maturityRequired: 'Intelligent', deploymentComplexity: 'Medium', edgeSplit: 20, cloudSplit: 80, twinIntegration: true },
  { id: 'factory-copilot', name: 'Factory Copilot', category: 'Factory Copilot', description: 'Conversational AI over your operational graph - query your factory in natural language, get contextual insights.', icon: 'bot', kpiImpact: ['Decision Velocity', 'Operator Productivity', 'Knowledge Retention'], maturityRequired: 'Autonomous', deploymentComplexity: 'Medium', edgeSplit: 10, cloudSplit: 90, twinIntegration: true },
  { id: 'worker-safety', name: 'Worker Safety Twin', category: 'Worker Safety Twin', description: 'Real-time ergonomic risk, environmental exposure, fatigue modeling, and proximity intelligence for workforce safety.', icon: 'users', kpiImpact: ['Safety Incidents', 'Compliance Cost', 'Worker Wellbeing'], maturityRequired: 'Intelligent', deploymentComplexity: 'Medium', edgeSplit: 60, cloudSplit: 40, twinIntegration: true },
];

export const useCases: UseCase[] = [
  {
    id: 'predictive-maintenance',
    title: 'Predictive Maintenance',
    description: 'Detect failure signatures before breakdown using asset twin behavioral models.',
    inputs: ['Vibration Sensors', 'Thermal Cameras', 'Current Signatures', 'Historical Maintenance'],
    edgeProcessing: ['Signal Filtering', 'Feature Extraction', 'Anomaly Pre-scoring', 'Local Alert'],
    cloudAnalytics: ['Azure Anomaly Detector', 'Digital Twin State', 'Failure Pattern Library', 'Fleet Benchmarking'],
    decisionLogic: ['Failure Probability Score', 'Maintenance Window Selection', 'Parts Procurement Trigger', 'Operator Notification'],
    outcomes: ['Maintenance Ticket', 'Work Order Creation', 'Part Pre-staging', 'Downtime Avoidance'],
    roi: '35% reduction in unplanned downtime',
    complexity: 'Medium',
    maturityRequired: 'Intelligent',
    industries: ['Automotive', 'Energy', 'Mining', 'Food & Beverage'],
  },
  {
    id: 'autonomous-condition-monitoring',
    title: 'Autonomous Condition Monitoring',
    description: 'Continuous asset health scoring with zero human intervention - self-adjusting thresholds.',
    inputs: ['Vibration', 'Temperature', 'Pressure', 'Flow Rate', 'Power Consumption'],
    edgeProcessing: ['Edge ML Inference', 'Threshold Adaptation', 'Local State Machine', 'Buffering'],
    cloudAnalytics: ['Azure Data Explorer (ADX)', 'Time-Series DB', 'Baseline Learning', 'Peer Comparison'],
    decisionLogic: ['Health Score Engine', 'Degradation Trajectory', 'Intervention Priority Queue'],
    outcomes: ['Health Dashboard Update', 'Alert Escalation', 'Autonomous Schedule Adjustment', 'Twin State Update'],
    roi: '28% improvement in OEE',
    complexity: 'Medium',
    maturityRequired: 'Intelligent',
    industries: ['Process', 'Discrete', 'Utilities'],
  },
  {
    id: 'carbon-optimization',
    title: 'Carbon Optimization',
    description: 'Closed-loop carbon control that balances production targets with emissions constraints in real time.',
    inputs: ['Energy Meters', 'Production Schedule', 'Grid Carbon Intensity', 'Process Parameters'],
    edgeProcessing: ['Energy Disaggregation', 'Scope 1 Calculation', 'Local Carbon Buffer'],
    cloudAnalytics: ['Carbon Twin', 'Grid API Integration', 'Simulation Engine', 'Offset Marketplace'],
    decisionLogic: ['Emission Budget Allocation', 'Production Scheduling Optimization', 'Renewable Shift Logic'],
    outcomes: ['Schedule Adjustment', 'Carbon Report', 'Offset Recommendation', 'ESG Dashboard Update'],
    roi: '22% reduction in Scope 1 emissions',
    complexity: 'High',
    maturityRequired: 'Intelligent',
    industries: ['Steel', 'Cement', 'Chemical', 'Energy'],
  },
  {
    id: 'digital-product-passport',
    title: 'Digital Product Passport',
    description: 'EU DPP-compliant traceability from raw material to end-of-life embedded in every product.',
    inputs: ['Material Origin', 'Process Parameters', 'Quality Data', 'Energy Consumption', 'Worker Records'],
    edgeProcessing: ['Data Capture at Line', 'Timestamp Anchoring', 'Local Validation'],
    cloudAnalytics: ['Blockchain Anchoring', 'Regulatory Mapping', 'Sustainability Calculator'],
    decisionLogic: ['Compliance Gate', 'Pass/Fail Scoring', 'Remediation Trigger'],
    outcomes: ['DPP Certificate', 'Regulatory Submission', 'Customer Transparency Portal', 'Recall Traceability'],
    roi: 'EU market access + 15% premium pricing',
    complexity: 'High',
    maturityRequired: 'Intelligent',
    industries: ['Automotive', 'Electronics', 'Textiles', 'Battery'],
  },
  {
    id: 'worker-safety-twin',
    title: 'Worker Safety Twin',
    description: 'Real-time digital twin of the human-machine environment for proactive safety management.',
    inputs: ['Wearable Biometrics', 'Vision AI', 'Zone Presence', 'Environmental Sensors', 'Equipment State'],
    edgeProcessing: ['Fatigue Detection', 'Proximity Alert', 'PPE Compliance Check'],
    cloudAnalytics: ['Safety Twin', 'Incident Pattern Analysis', 'Regulatory Reporting', 'Training Gap Analysis'],
    decisionLogic: ['Risk Score Engine', 'Intervention Trigger', 'Autonomous Zone Access Control'],
    outcomes: ['Safety Alert', 'Equipment Slowdown', 'Supervisor Notification', 'Insurance Reporting'],
    roi: '60% reduction in recordable incidents',
    complexity: 'Medium',
    maturityRequired: 'Intelligent',
    industries: ['Mining', 'Construction', 'Chemical', 'Automotive'],
  },
  {
    id: 'ai-quality-inspection',
    title: 'AI Quality Inspection',
    description: 'Computer vision at line speed with zero sampling bias and full defect traceability to process root cause.',
    inputs: ['Line Cameras', 'Process Parameters', 'Material Specs', 'Historical Defect Library'],
    edgeProcessing: ['Real-Time Inference', 'Defect Classification', 'Local Decision', 'Reject Trigger'],
    cloudAnalytics: ['Model Retraining', 'Defect Trend Analysis', 'Process Correlation', 'SPC Integration'],
    decisionLogic: ['Defect Gate', 'Process Parameter Recommendation', 'Escalation Logic'],
    outcomes: ['Accept/Reject Signal', 'Process Adjustment', 'Quality Report', 'Supplier Feedback'],
    roi: '73% reduction in customer defect escapes',
    complexity: 'High',
    maturityRequired: 'Intelligent',
    industries: ['Automotive', 'Electronics', 'Pharma', 'Food & Beverage'],
  },
  {
    id: 'factory-as-a-service',
    title: 'Factory-as-a-Service',
    description: 'Expose factory capacity as a digital service - demand-driven production with full digital orchestration.',
    inputs: ['Customer Orders', 'Capacity Twin', 'Resource State', 'Quality Standards'],
    edgeProcessing: ['Capacity Sensing', 'Constraint Detection', 'Local Scheduling'],
    cloudAnalytics: ['Production Optimization', 'Digital Marketplace', 'SLA Tracking'],
    decisionLogic: ['Dynamic Scheduling', 'Constraint Resolution', 'Pricing Engine'],
    outcomes: ['Order Confirmation', 'Production Schedule', 'Customer Portal Update', 'Revenue Recognition'],
    roi: '40% increase in asset utilization',
    complexity: 'High',
    maturityRequired: 'Autonomous',
    industries: ['Electronics', 'Automotive', 'Aerospace'],
  },
  {
    id: 'heat-exchanger-optimization',
    title: 'Heat Exchanger Optimization',
    description: 'Thermal efficiency twin that continuously optimizes cleaning schedules and operating setpoints.',
    inputs: ['Temperature Differential', 'Flow Rate', 'Pressure Drop', 'Fouling Sensors'],
    edgeProcessing: ['Efficiency Calculation', 'Fouling Rate Detection', 'Local Optimization Loop'],
    cloudAnalytics: ['Thermal Twin', 'Cleaning Schedule Optimizer', 'Energy Benchmarking'],
    decisionLogic: ['Cleaning Trigger', 'Setpoint Recommendation', 'Shutdown Risk Assessment'],
    outcomes: ['Cleaning Work Order', 'Setpoint Update', 'Energy Saving Report', 'Capital Deferral'],
    roi: '18% energy savings + 30% cleaning cost reduction',
    complexity: 'Low',
    maturityRequired: 'Intelligent',
    industries: ['Chemical', 'Oil & Gas', 'Power', 'Food & Beverage'],
  },
  {
    id: 'root-cause-intelligence',
    title: 'Root Cause Intelligence',
    description: 'AI-powered causal chain analysis that traverses the operational graph to find true failure origin.',
    inputs: ['Alarm Storm Data', 'Topology Graph', 'Maintenance History', 'Process Parameters'],
    edgeProcessing: ['Alarm Suppression', 'First Principle Detection', 'Causal Candidate Extraction'],
    cloudAnalytics: ['Graph Neural Network', 'Causal Model Library', 'Historical Pattern Match'],
    decisionLogic: ['Root Cause Ranking', 'Confidence Scoring', 'Corrective Action Library'],
    outcomes: ['RCA Report', 'CAPA Generation', 'CMDB Update', 'Knowledge Graph Enrichment'],
    roi: '55% reduction in MTTR',
    complexity: 'Medium',
    maturityRequired: 'Intelligent',
    industries: ['Process', 'Energy', 'Pharma', 'Utilities'],
  },
  {
    id: 'green-hydrogen-twin',
    title: 'Green Hydrogen Twin',
    description: 'Electrolyzer digital twin that optimizes hydrogen production against renewable energy availability.',
    inputs: ['Renewable Energy Signal', 'Grid Intensity', 'Electrolyzer State', 'Storage Level'],
    edgeProcessing: ['Stack Performance Model', 'Efficiency Calculation', 'Degradation Tracking'],
    cloudAnalytics: ['Energy Market Integration', 'Production Twin', 'Hydrogen Quality Model'],
    decisionLogic: ['Production Rate Optimization', 'Stack Switch Logic', 'Market Dispatch Decision'],
    outcomes: ['Production Schedule', 'Grid Signal Response', 'Hydrogen Quality Certificate', 'Carbon Report'],
    roi: '25% reduction in levelized cost of hydrogen',
    complexity: 'High',
    maturityRequired: 'Autonomous',
    industries: ['Energy', 'Steel', 'Chemical', 'Transport'],
  },
];

export const plantSites: PlantSite[] = [
  { id: 'sg1', name: 'Singapore Plant', location: 'Jurong Island', country: 'Singapore', lat: 1.26, lng: 103.67, maturity: 'Intelligent', assets: 4280, incidents: 2, compliance: 94, activeTwins: 12 },
  { id: 'de1', name: 'Stuttgart Werk', location: 'Stuttgart', country: 'Germany', lat: 48.78, lng: 9.18, maturity: 'Autonomous', assets: 6100, incidents: 0, compliance: 99, activeTwins: 28 },
  { id: 'us1', name: 'Detroit Assembly', location: 'Detroit, MI', country: 'USA', lat: 42.33, lng: -83.05, maturity: 'Contextual', assets: 3400, incidents: 5, compliance: 78, activeTwins: 6 },
  { id: 'cn1', name: 'Shenzhen Factory', location: 'Shenzhen', country: 'China', lat: 22.54, lng: 114.06, maturity: 'Visible', assets: 5200, incidents: 8, compliance: 71, activeTwins: 3 },
  { id: 'in1', name: 'Pune Hub', location: 'Pune', country: 'India', lat: 18.52, lng: 73.86, maturity: 'Fragmented', assets: 1800, incidents: 14, compliance: 52, activeTwins: 0 },
  { id: 'br1', name: 'São Paulo Works', location: 'São Paulo', country: 'Brazil', lat: -23.55, lng: -46.63, maturity: 'Visible', assets: 2100, incidents: 6, compliance: 68, activeTwins: 2 },
  { id: 'uk1', name: 'Manchester Mill', location: 'Manchester', country: 'UK', lat: 53.48, lng: -2.24, maturity: 'Contextual', assets: 2900, incidents: 3, compliance: 85, activeTwins: 7 },
];

export const cioKPIs: KPI[] = [
  { label: 'OT Asset Visibility',   value: '85',  unit: '%',     trend: 'up',   delta: '+40 pts vs baseline'      },
  { label: 'Unplanned Downtime',    value: '35',  unit: '%↓',    trend: 'down', delta: '−30–40% reduction'         },
  { label: 'MTTR Improvement',      value: '30',  unit: '%↓',    trend: 'down', delta: '−25–35% faster resolution' },
  { label: 'OT Maturity Score',     value: '3.5', unit: 'pts↑',  trend: 'up',   delta: '+3–4 pts gained'           },
  { label: 'Deployment Velocity',   value: '45',  unit: '%↓',    trend: 'down', delta: '−40–50% faster delivery'   },
  { label: 'Sustainability Score',  value: '20',  unit: '%↑',    trend: 'up',   delta: '+15–25% improvement'       },
  { label: 'Active Digital Twins',  value: '40',  unit: 'twins', trend: 'up',   delta: 'Phase 2 onwards'           },
  { label: 'Operational Resilience',value: '18',  unit: '%↑',    trend: 'up',   delta: '+15–20% stronger posture'  },
];

export const fragmentationProblems = [
  { id: 'unknown', label: 'Unknown Devices', severity: 'critical', count: '847', icon: 'help-circle' },
  { id: 'shadow-ot', label: 'Shadow OT', severity: 'critical', count: '143', icon: 'eye-off' },
  { id: 'stale-cmdb', label: 'Stale CMDB Records', severity: 'warning', count: '2,341', icon: 'database' },
  { id: 'unsupported', label: 'Unsupported Protocols', severity: 'warning', count: '31', icon: 'alert-triangle' },
  { id: 'dup-signals', label: 'Duplicate Signals', severity: 'warning', count: '1,204', icon: 'copy' },
  { id: 'dark-zones', label: 'Dark Operational Zones', severity: 'critical', count: '8', icon: 'lock' },
  { id: 'disconnected', label: 'Disconnected PLCs', severity: 'critical', count: '67', icon: 'unplug' },
  { id: 'stale-fw', label: 'EOL Firmware', severity: 'warning', count: '312', icon: 'clock' },
];

export const visibilityCapabilities = [
  { id: 'discovery', label: 'OT Asset Discovery', desc: 'Passive network scanning with zero operational impact', kpi: '85%+ asset coverage', icon: 'search' },
  { id: 'cmdb', label: 'OT CMDB', desc: 'Auto-populated, continuously reconciled asset registry', kpi: 'Near-complete sync', icon: 'database' },
  { id: 'fingerprint', label: 'Device Fingerprinting', desc: 'Vendor, firmware, and behavior-based identity', kpi: '600+ vendors supported', icon: 'scan' },
  { id: 'monitoring', label: 'OT Monitoring', desc: 'Real-time telemetry from all Purdue levels', kpi: 'Sub-second latency', icon: 'activity' },
  { id: 'drift', label: 'Drift Detection', desc: 'Configuration change detection with audit trail', kpi: 'Near-real-time detection', icon: 'git-branch' },
  { id: 'protocol', label: 'Protocol Awareness', desc: '150+ industrial protocols decoded and normalized', kpi: '150+ protocols', icon: 'network' },
  { id: 'segmentation', label: 'Network Segmentation', desc: 'Purdue/IEC 62443 zone mapping and enforcement', kpi: 'Zone compliance measured', icon: 'layers' },
  { id: 'dmz', label: 'OT DMZ Visibility', desc: 'Full visibility into IT/OT convergence points', kpi: 'DMZ coverage: 100%', icon: 'shield' },
];

export const twinTypes = [
  { id: 'asset', label: 'Asset Twin', desc: 'Individual equipment - motor, pump, heat exchanger', color: '#005EB8', icon: 'package' },
  { id: 'process', label: 'Process Twin', desc: 'Production line or chemical process simulation', color: '#00A3E0', icon: 'workflow' },
  { id: 'factory', label: 'Factory Twin', desc: 'Complete facility with all systems and flows', color: '#12B3A8', icon: 'factory' },
  { id: 'carbon', label: 'Carbon Twin', desc: 'Real-time emissions model with optimization loops', color: '#34D399', icon: 'leaf' },
  { id: 'worker', label: 'Worker Twin', desc: 'Workforce safety, ergonomics, and productivity', color: '#F5A623', icon: 'users' },
  { id: 'sustainability', label: 'Sustainability Twin', desc: 'ESG metrics, energy flows, circular economy', color: '#10B981', icon: 'recycle' },
  { id: 'operational', label: 'Operational Twin', desc: 'Live operational state with autonomous control loops', color: '#003B73', icon: 'gauge' },
];

export const autonomousScenarios = [
  {
    id: 'vibration',
    title: 'Vibration Anomaly',
    trigger: 'Vibration spike detected: 4.2g on Motor B-7',
    steps: [
      'Topology correlation: Motor B-7 → Line 3 → Assembly Cell 4',
      'Impact evaluation: 340 units/hr at risk',
      'Twin simulation: 87% failure probability in 4.2 hours',
      'Remediation: Schedule PdM window at 06:00 shift change',
      'Parts staging: Bearing assembly pre-ordered from CMMS',
      'Operator notification: Maintenance lead + Shift supervisor',
      'Twin updated: Failure averted, health score restored',
    ],
    outcome: 'Downtime avoided. Estimated saving: $47,000',
    severity: 'warning',
    icon: 'activity',
  },
  {
    id: 'unauthorized',
    title: 'Unauthorized Device',
    trigger: 'Unknown device detected: 192.168.12.87 in Zone 2',
    steps: [
      'Device fingerprinting: Unknown Windows XP endpoint',
      'Zone policy check: IEC 62443 violation - Level 1 boundary',
      'Network isolation: Port blocked within 90ms',
      'CISO alert: Incident ticket #OT-2847 created',
      'Topology impact: 0 production disruption (isolated)',
      'Forensics initiated: Device captured for analysis',
      'Policy updated: New detection signature added',
    ],
    outcome: 'Threat contained. Zero production impact.',
    severity: 'critical',
    icon: 'shield',
  },
  {
    id: 'energy',
    title: 'Energy Anomaly',
    trigger: 'Compressor A energy consumption +31% above baseline',
    steps: [
      'Baseline comparison: 187 kW vs. 143 kW expected',
      'Process correlation: Suction pressure drop detected',
      'Carbon twin update: +12 tCO₂ projected this shift',
      'Root cause: Filter fouling - efficiency degraded 23%',
      'Recommendation: Cleaning at next planned shutdown',
      'Process adjustment: Setpoint optimized to -8% energy',
      'ESG dashboard: Scope 1 forecast recalculated',
    ],
    outcome: 'Energy waste recovered. €3,200/day saved.',
    severity: 'warning',
    icon: 'zap',
  },
  {
    id: 'overheating',
    title: 'Thermal Overrun',
    trigger: 'Spindle temperature 92°C - 15°C above threshold',
    steps: [
      'Thermal twin activated: Degradation model running',
      'Production impact: CNC Cell 7 at risk in 18 minutes',
      'Coolant system check: Flow rate nominal - bearing failure',
      'Autonomous slowdown: Speed reduced 35% to extend window',
      'Operator alert: 18-minute countdown + recommended action',
      'Maintenance dispatched: Bearing kit en route from crib',
      'Quality hold: 47 parts flagged for re-inspection',
    ],
    outcome: 'Machine saved. Controlled intervention. No scrap.',
    severity: 'critical',
    icon: 'gauge',
  },
];

// Per-scene, per-stakeholder lens content - used by StakeholderLens component
export const sceneLens: Record<number, Partial<Record<string, { icon: string; insight: string; action: string }>>> = {
  1: {
    CIO: { icon: '', insight: '847 unknown OT assets are unmanaged operational liabilities. Every AI investment fails without this foundation.', action: 'Quantify your risk exposure' },
    CISO: { icon: '', insight: 'Each unmanaged OT endpoint is an undetected lateral movement vector. You cannot defend what you cannot see.', action: 'Map your attack surface' },
    OTArchitect: { icon: '', insight: '31 unsupported protocols are violating IEC 62443 zone boundaries. Shadow OT breaks your architectural integrity.', action: 'Audit zone compliance' },
    PlantManager: { icon: '', insight: '8 dark operational zones are producing zero-confidence telemetry. Production decisions are being made blind.', action: 'Illuminate your floor' },
    ManufacturingIT: { icon: '', insight: 'Stale CMDB means every IT/OT integration is built on fiction. Real-time asset sync is the fix.', action: 'Sync your CMDB' },
    ReliabilityEngineer: { icon: '', insight: 'Unknown devices cannot be maintained. Fragmentation makes predictive maintenance statistically meaningless.', action: 'Start with asset truth' },
    SustainabilityOfficer: { icon: '', insight: 'You cannot measure what you cannot see. Carbon twin accuracy depends on full asset coverage.', action: 'Establish energy baseline' },
    CTO: { icon: '', insight: 'No API, pipeline, or AI model can serve data from assets you don\'t know exist. Visibility is your data foundation.', action: 'Design from truth' },
    OperationsLead: { icon: '', insight: '8 dark zones mean operations decisions are made without full situational awareness - every shift.', action: 'Recover operational sight' },
    PlatformEngineeringLead: { icon: '', insight: 'Platform services cannot be deployed to unknown infrastructure. Visibility is your deployment prerequisite.', action: 'Build on known ground' },
  },
  2: {
    CIO: { icon: '', insight: 'Comprehensive asset visibility means operational risk is managed, insurable, and auditable. Every unknown device is a liability you can now close.', action: 'Calculate ROI of visibility' },
    CISO: { icon: '', insight: 'Zero Trust starts at Level 0. Every device fingerprinted, every zone bounded, every protocol known and monitored.', action: 'Enable Zero Trust OT' },
    OTArchitect: { icon: '', insight: 'IEC 62443 zone mapping applied across all Purdue levels. DMZ architecture enforced with continuous policy validation.', action: 'View architecture details' },
    PlantManager: { icon: '', insight: 'Confirmed asset coverage means OEE calculations are finally based on operational truth, not floor estimates.', action: 'Activate production visibility' },
    ManufacturingIT: { icon: '', insight: '150+ protocols normalized into a unified data fabric. Every integration now works from a single source of truth.', action: 'Explore protocol coverage' },
    ReliabilityEngineer: { icon: '', insight: 'Near-real-time drift detection means configuration deviations are caught before they become failures.', action: 'Set up drift alerts' },
    SustainabilityOfficer: { icon: '', insight: 'Full Purdue coverage means energy metering at every level - enabling precise Scope 1 and Scope 2 accounting.', action: 'Enable energy visibility' },
    CTO: { icon: '', insight: 'Centralized OT monitoring creates the real-time operational data layer your AI pipelines need to function at scale.', action: 'Design data architecture' },
    OperationsLead: { icon: '', insight: 'Mean time to identify an asset anomaly drops from hours to 4 minutes - before it becomes a production incident.', action: 'Accelerate detection' },
    PlatformEngineeringLead: { icon: '', insight: 'OT CMDB as a service: auto-populated, always current, API-accessible - the infrastructure registry your platform needs.', action: 'Integrate with CMDB API' },
  },
  3: {
    CIO: { icon: '', insight: 'The operational knowledge graph creates the semantic layer that makes AI queries on your factory actually meaningful.', action: 'Explore enterprise graph' },
    CISO: { icon: '', insight: 'Click any asset to see its vulnerability profile, dependency chain, and blast radius - all in real time.', action: 'Audit asset dependencies' },
    OTArchitect: { icon: '', insight: 'Unified Namespace + Asset Administration Shell: every asset has a digital identity, every relationship is queryable.', action: 'Design your UNS topology' },
    PlantManager: { icon: '', insight: 'Clicking a motor reveals its dependencies, maintenance history, and energy consumption - in one view.', action: 'Explore asset context' },
    ReliabilityEngineer: { icon: '', insight: 'Operational lineage: trace any failure back through its dependency graph to find the true root cause.', action: 'Trace failure lineage' },
    SustainabilityOfficer: { icon: '', insight: 'Energy consumption is contextualized at every node - from motor to line to facility to enterprise.', action: 'Map energy flows' },
  },
  4: {
    CIO: { icon: '', insight: 'A digital twin that grew from operational truth - not a CAD file - makes business-impacting simulations possible.', action: 'View twin ROI model' },
    OTArchitect: { icon: '', insight: 'Sensor → Edge → Cloud → Decision → Outcome: the reference architecture for every industrial AI use case.', action: 'Download architecture' },
    ReliabilityEngineer: { icon: '', insight: 'Asset twin behavioral models detect failure signatures 4–6 hours before physical breakdown.', action: 'Activate PdM twin' },
    SustainabilityOfficer: { icon: '', insight: 'Carbon Twin simulates emissions impact of production decisions before they are executed.', action: 'Configure carbon twin' },
    PlantManager: { icon: '', insight: 'Factory twin runs what-if scenarios - change schedules, shift patterns, or maintenance windows without touching the floor.', action: 'Run factory simulation' },
  },
  5: {
    CIO: { icon: '', insight: 'Autonomous operations eliminate reactive decision cycles. MTTR drops from hours to minutes with zero operator intervention.', action: 'Review incident ROI' },
    CISO: { icon: '', insight: 'Unauthorized device detection + network isolation in under 90ms - before lateral movement occurs.', action: 'Test threat response' },
    PlantManager: { icon: '', insight: 'The factory responds to anomalies faster than any shift supervisor - correlating topology, telemetry, and history.', action: 'Configure alert thresholds' },
    ReliabilityEngineer: { icon: '', insight: 'Autonomous maintenance scheduling selects optimal windows based on production plan, parts availability, and risk score.', action: 'Set up autonomous maintenance' },
    OperationsLead: { icon: '', insight: 'Every autonomous action is logged with full context - why it happened, what it changed, what was avoided.', action: 'Review action log' },
  },
};

export const storyScenes = [
  { id: 'hero',     label: 'Start Here',               icon: 'home', short: 'Intro'    },
  { id: 'scene1',  label: 'The Invisible Factory',     icon: 'factory', short: 'Problem'  },
  { id: 'scene2',  label: 'OT Visibility',             icon: 'eye', short: 'Visibility'},
  { id: 'scene3',  label: 'Operational Graph',         icon: 'network', short: 'Context'  },
  { id: 'scene4',  label: 'Digital Twin',              icon: 'cpu', short: 'Twin'     },
  { id: 'scene5',      label: 'Autonomous Ops',            icon: 'bot', short: 'Autonomy' },
  { id: 'bigpicture',  label: 'Ecosystem Map',             icon: 'map', short: 'Map'      },
  { id: 'value-chain', label: 'Visibility to Value',       icon: 'layers', short: 'Journey'  },
  { id: 'fof',         label: 'Factory of the Future',     icon: 'building-2', short: 'FoF'      },
  { id: 'target',  label: 'Target State Blueprint',    icon: 'target', short: 'Target'   },
  { id: 'scene6',  label: 'OT Services',               icon: 'package', short: 'Services' },
  { id: 'scene7',  label: 'Global Governance',         icon: 'globe', short: 'Govern'   },
  { id: 'roadmap', label: 'Transformation Roadmap',    icon: 'map-pin', short: 'Roadmap'  },
  { id: 'deloitte',label: 'Programme Structure',        icon: 'briefcase', short: 'Programme'},
  { id: 'scene8',  label: 'Use Case Studio',           icon: 'bar-chart-2', short: 'Use Cases'},
  { id: 'cio',     label: 'Command Center',            icon: 'layout-dashboard', short: 'Cockpit'  },
];

export const globalKPIs = {
  totalAssets: 25780,
  managedAssets: 24241,
  visibilityScore: 94,
  activeIncidents: 18,
  avgCompliance: 81,
  activeTwins: 58,
  deployedServices: 127,
  mttrMinutes: 47,
};

// ─── Factory of the Future ────────────────────────────────────────────────────

export const fofUseCases = [
  {
    id: 'digital-twin',
    number: 1,
    icon: 'cpu',
    title: 'Digital Twins',
    tagline: 'The living operational mirror - not a 3D model',
    description: 'Asset visibility provides the continuous data feed that makes digital twins alive and accurate. Without knowing what assets exist, how they connect, and their real-time state, a twin is a static model that decays from day one.',
    visibilityGate: 'High asset coverage + protocol normalization + topology mapping',
    businessValue: 'Significant',
    businessDetail: 'per facility via avoided failures and predictive operations',
    operationalValue: 'Less unplanned downtime',
    efficiency: 'OEE improvement',
    secondOrder: ['Supply chain simulation capability', 'Regulatory digital thread', 'Foundation for autonomous ops'],
    proof: { org: 'Global Biologics Manufacturer', result: 'Asset twins across multiple plants - measurable reduction in equipment failures - 18-month programme' },
    color: '#005EB8', bg: '#EAF4FF',
  },
  {
    id: 'predictive-maint',
    number: 2,
    icon: 'wrench',
    title: 'Predictive Maintenance',
    tagline: 'Fix before it fails - zero production surprises',
    description: 'Real-time asset telemetry feeds ML failure models that predict equipment degradation days before breakdown. Maintenance becomes a planned activity, not an emergency scramble that halts production.',
    visibilityGate: 'Sensor-level telemetry from all critical assets with protocol-normalized time-series',
    businessValue: 'Material',
    businessDetail: 'per plant in avoided downtime and emergency-maintenance labour',
    operationalValue: 'Fewer unplanned stops',
    efficiency: 'Lower maintenance cost',
    secondOrder: ['Extended asset lifetimes', 'Spare-parts inventory reduction', 'Shift to outcome-based contracts'],
    proof: { org: 'Top-5 Pharma Contract Manufacturer', result: 'Multiple assets under PdM - materially faster MTTR - 12-month programme' },
    color: '#00A3E0', bg: '#E0F4FF',
  },
  {
    id: 'carbon-twin',
    number: 3,
    icon: 'leaf',
    title: 'Carbon & Energy Twin',
    tagline: 'Scope 1/2 emissions tracked, modelled, and optimised in real time',
    description: 'A carbon twin requires knowing exactly where energy flows through every asset, process, and utility. Visibility enables closed-loop carbon control that turns ESG commitments into an engineering problem you can solve.',
    visibilityGate: 'Energy metering at asset level + process-parameter correlation across L0–L3',
    businessValue: 'Material',
    businessDetail: 'in energy savings + carbon credit value at full deployment',
    operationalValue: 'Measurable Scope 1 reduction',
    efficiency: 'Lower energy intensity / unit',
    secondOrder: ['EU Taxonomy alignment', 'Scope 3 supplier data chain', 'Green premium pricing capability'],
    proof: { org: 'European Specialty Chemical Producer', result: 'Measured Scope 1 reduction achieved - verified carbon credits generated - 14-month programme' },
    color: '#12B3A8', bg: '#E6FAF8',
  },
  {
    id: 'ai-quality',
    number: 4,
    icon: 'scan',
    title: 'AI Quality Inspection',
    tagline: 'Zero defects at line speed - full traceability to root cause',
    description: 'Computer vision + process-parameter correlation catches defects the moment they form. Asset visibility provides the process context that turns a detection signal into a root-cause-linked intervention - critical in GxP-regulated manufacturing.',
    visibilityGate: 'Machine-level process params + vision inference layer + OT operational-graph context',
    businessValue: 'Significant',
    businessDetail: 'in scrap, rework, and customer-return cost avoidance',
    operationalValue: 'Fewer defect escapes',
    efficiency: 'Lower scrap rate',
    secondOrder: ['GxP-ready quality digital thread', 'Batch release acceleration', 'Customer audit readiness on demand'],
    proof: { org: 'Life Sciences Equipment Manufacturer', result: 'AI inspection deployed on production lines - material reduction in customer returns - 9-month programme' },
    color: '#F5A623', bg: '#FFFBEB',
  },
  {
    id: 'autonomous-ops',
    number: 5,
    icon: 'bot',
    title: 'Autonomous Operations',
    tagline: 'The factory that responds, adapts, and self-heals without operator intervention',
    description: 'Autonomous operations is the convergence of visibility, context, twins, and intelligence. Every automated decision is only trustworthy if it is grounded in accurate, real-time operational state. Visibility is the prerequisite for trust in automation.',
    visibilityGate: 'Full maturity stack - Visible → Contextual → Intelligent - all prerequisite capabilities active',
    businessValue: 'Transformational',
    businessDetail: 'blended across downtime, quality, energy, and labour at full deployment',
    operationalValue: 'Majority of events resolved autonomously',
    efficiency: 'Near-zero unplanned stops',
    secondOrder: ['Factory-as-a-Service model enablement', 'Workforce redeployment to higher-value tasks', 'Continuous regulatory compliance'],
    proof: { org: 'Tier-1 Automotive OEM Supplier', result: 'Majority of events resolved autonomously · materially faster response vs prior benchmark · 24-month programme' },
    color: '#6366F1', bg: '#F0F0FF',
  },
];

export const marketProofPoints = [
  {
    icon: 'flask-conical',
    sector: 'Pharma & Life Sciences',
    company: 'Global Top-10 Pharmaceutical Manufacturer',
    headline: 'Comprehensive OT asset visibility achieved within first year',
    metrics: ['Significant maintenance cost reduction', 'Faster incident response', 'Critical vulnerabilities identified and remediated'],
    quote: 'We could not activate a single digital twin until we knew what we had. Visibility was the unlock.',
  },
  {
    icon: 'settings',
    sector: 'Industrial Equipment',
    company: 'European Life Sciences Equipment Producer',
    headline: 'Autonomous quality inspection across 3 lines',
    metrics: ['Material reduction in customer returns', 'GxP audit pack generated on demand', '9-month implementation'],
    quote: 'Our FDA audit preparation time dropped from 3 weeks to 2 hours once every asset and process was digitally traceable.',
  },
  {
    icon: 'leaf',
    sector: 'Specialty Chemicals',
    company: 'Mid-size European Chemical Manufacturer',
    headline: 'Carbon twin enables measurable Scope 1 reduction',
    metrics: ['Quantified energy savings', 'Carbon reporting automated', 'Multi-plant rollout completed'],
    quote: 'The carbon twin turned sustainability from a reporting obligation into an operational lever we actively manage every shift.',
  },
];

// ─── Target State Blueprint ───────────────────────────────────────────────────

export const targetStateKPIs = [
  { metric: 'OT Asset Visibility',      current: 'Partial / estimated',  target: '≥ 85% confirmed',         months: 6,  color: '#005EB8', icon: 'eye'  },
  { metric: 'Unplanned Downtime',        current: 'Baseline',             target: '−30 to −40%',             months: 18, color: '#00A3E0', icon: 'alert-triangle'  },
  { metric: 'Active Digital Twins',      current: 'None',                 target: 'Critical assets covered', months: 24, color: '#12B3A8', icon: 'cpu' },
  { metric: 'Scope 1 Emissions',         current: 'Baseline (measured)',  target: 'Measurable reduction',    months: 30, color: '#10B981', icon: 'leaf'  },
  { metric: 'Mean Time to Repair',       current: 'Baseline',             target: '−25 to −35%',             months: 18, color: '#F5A623', icon: 'clock' },
  { metric: 'OT Security Compliance',   current: 'Partial / ad hoc',     target: 'IEC 62443 Level 2–3',     months: 12, color: '#D64545', icon: 'shield'  },
  { metric: 'Batch Release Cycle',       current: 'Baseline',             target: '−15 to −25%',             months: 24, color: '#6366F1', icon: 'flask-conical' },
  { metric: 'GxP Audit Readiness',       current: 'Manual / weeks',       target: 'Structured / days',       months: 18, color: '#003B73', icon: 'check-circle' },
];

export const peerBenchmarks = [
  { org: 'Current State',                maturity: 'Fragmented - Partial Visibility', visibility: 40, twins: 0,  autonomy: 5,  color: '#D64545' },
  { org: 'Industry Average (Life Sci.)', maturity: 'Visible',                         visibility: 58, twins: 8,  autonomy: 15, color: '#F5A623' },
  { org: 'Industry Leaders (Top 25%)',   maturity: 'Contextual',                      visibility: 81, twins: 34, autonomy: 38, color: '#00A3E0' },
  { org: 'Best-in-Class (Top 5%)',       maturity: 'Intelligent',                     visibility: 96, twins: 80, autonomy: 71, color: '#12B3A8' },
  { org: 'Target State',                 maturity: 'Intelligent - Autonomous',        visibility: 90, twins: 60, autonomy: 65, color: '#005EB8' },
];

export const lifeSciencesCapabilities = [
  { icon: 'file-check', title: 'FDA 21 CFR Part 11', desc: 'Electronic records and audit trail for every automated action and system change' },
  { icon: 'git-merge', title: 'GxP Digital Thread', desc: 'End-to-end data integrity from raw material receipt to batch release - fully traceable' },
  { icon: 'search', title: 'Cleanroom OT Visibility', desc: 'Passive asset discovery with zero cleanroom contamination risk - qualified approach' },
  { icon: 'cpu', title: 'Batch Process Twin', desc: 'Digital twin for bioprocess fermentation with parameter-to-quality correlation' },
  { icon: 'flask-conical', title: 'PAT Integration', desc: 'Process Analytical Technology data feeds into quality twin for real-time release decisions' },
  { icon: 'check-circle', title: 'Annex 11 Compliance', desc: 'EU GMP computerised systems validation built into the platform from day one' },
];

// ─── Transformation Roadmap ───────────────────────────────────────────────────

export const roadmapPhases = [
  {
    id: 'foundation',
    number: 1,
    title: 'Foundation',
    subtitle: 'See Everything',
    duration: '0 – 6 Months',
    color: '#F5A623',
    bg: '#FFFBEB',
    icon: 'layers',
    summary: 'Establish the operational truth layer. Every asset discovered, mapped, and governed before a single twin is activated.',
    milestones: [
      { week: 4,  label: 'OT Asset Discovery',      detail: 'Passive scan across all Purdue levels - asset fingerprinting with zero production impact' },
      { week: 8,  label: 'Network Topology Map',    detail: 'IT/OT boundary defined, DMZ architecture validated, IEC 62443 zone segmentation confirmed' },
      { week: 12, label: 'CMDB Populated',           detail: 'All assets in the asset management system with lifecycle status, compliance state, and GxP flags' },
      { week: 16, label: 'OT Security Baseline',    detail: 'IEC 62443 gap assessment complete, remediation plan approved and resourced' },
      { week: 20, label: 'Data Connectivity Layer', detail: 'Protocol normalisation active - OPC-UA, Modbus, HART, S7, EtherNet/IP all flowing into unified data fabric' },
      { week: 24, label: 'Phase Gate',              detail: 'Asset coverage target met · security baseline established · data quality validated · GxP inventory confirmed' },
    ],
    quickWins: [
      { day: 30, win: '800+ unknown devices identified and classified - operational risk quantified for the first time' },
      { day: 60, win: 'OT/IT firewall rule validation complete - critical rule conflicts resolved, compliance gaps closed' },
      { day: 90, win: 'First live compliance dashboard - IEC 62443 and GxP coverage visible in real time to stakeholders' },
    ],
    prerequisites: [
      'Network access approval for passive scanning (zero production impact)',
      'IT/OT firewall change process agreed with CISO and operations',
      'CMDB / ITSM system identified and API access granted',
      'GxP inventory scope agreed with QA and regulatory affairs',
    ],
    integrations: ['ServiceNow / existing CMDB', 'Active Directory', 'Network management system (NMS)'],
    deliverables: ['Complete OT Asset Inventory', 'Network topology diagram', 'IEC 62443 gap report', 'GxP-flagged asset register'],
  },
  {
    id: 'intelligence',
    number: 2,
    title: 'Intelligence',
    subtitle: 'Understand Everything',
    duration: '6 – 18 Months',
    color: '#005EB8',
    bg: '#EAF4FF',
    icon: 'cpu',
    summary: 'Activate digital twins, build the operational knowledge graph, and deploy predictive intelligence across critical asset classes.',
    milestones: [
      { week: 28, label: 'Operational Knowledge Graph', detail: 'Semantic relationships between assets, processes, quality parameters, and maintenance records' },
      { week: 32, label: 'First 20 Digital Twins',       detail: 'Critical production equipment with live telemetry feeds and established behavioural baselines' },
      { week: 40, label: 'Predictive Maintenance Live',  detail: 'ML failure models deployed for top-10 critical assets ranked by downtime impact' },
      { week: 48, label: 'Carbon & Energy Twin',          detail: 'Scope 1/2 emissions tracked in real time at asset and process level across all plants' },
      { week: 56, label: 'AI Quality Inspection',         detail: '3 assembly lines with computer vision + process-parameter correlation - GxP-validated approach' },
      { week: 72, label: 'Phase Gate',                   detail: 'Core twins active · PdM accuracy validated · carbon baseline established · GxP audit trail confirmed' },
    ],
    quickWins: [
      { day: 210, win: 'First predictive alert prevents unplanned shutdown - $180K saving documented and communicated to leadership' },
      { day: 240, win: 'Carbon twin identifies 3 optimisation opportunities - €420K annual saving quantified and approved for implementation' },
      { day: 270, win: 'AI quality system catches defect class previously discovered only at end-of-line customer inspection' },
    ],
    prerequisites: [
      'Phase 1 complete - asset coverage target met and data connectivity layer operational',
      'Cloud analytics environment provisioned (Azure Data Explorer / TwinMaker)',
      'GxP data governance framework and 21 CFR Part 11 validation approach approved',
      'ML model validation process agreed with quality assurance',
    ],
    integrations: ['SAP S/4HANA (ERP)', 'OSIsoft PI / AVEVA Historian', 'SAP PM / Maximo (EAM)', 'LIMS', 'MES'],
    deliverables: ['80 digital twins', 'PdM on top-10 assets', 'Carbon twin baseline', 'AI quality on 3 lines', 'GxP audit trail live'],
  },
  {
    id: 'autonomy',
    number: 3,
    title: 'Autonomy',
    subtitle: 'Operate Everything',
    duration: '18 – 36 Months',
    color: '#12B3A8',
    bg: '#E6FAF8',
    icon: 'bot',
    summary: 'Deploy autonomous orchestration, self-healing operations, and continuous GxP compliance monitoring across the full manufacturing network.',
    milestones: [
      { week: 80,  label: 'Autonomous Event Response',  detail: 'Majority of operational events resolved without human intervention - validated governance framework active' },
      { week: 88,  label: 'Digital Product Passport',   detail: 'End-to-end product lifecycle traceability from raw material to customer delivery - EU DPP compliant' },
      { week: 96,  label: 'Factory Copilot Deployed',   detail: 'LLM-powered conversational interface over the full operational graph for every role and shift' },
      { week: 104, label: 'Worker Safety Twin',          detail: 'Real-time ergonomic risk and environmental exposure monitoring across all production zones' },
      { week: 120, label: 'Multi-Site Rollout',          detail: 'Full platform scaled across facilities under unified governance and policy enforcement' },
      { week: 144, label: 'Target State Validated ',   detail: 'All KPI targets met · continuous improvement loop active · GxP audit continuous · IEC 62443 Level 3 maintained' },
    ],
    quickWins: [
      { day: 570, win: 'First autonomous batch parameter adjustment executed - validated and signed off by QA, zero manual intervention required' },
      { day: 600, win: 'Regulatory inspection readiness on demand - full audit pack generated in <2 hours vs 3 weeks previously' },
      { day: 630, win: 'Multi-site OT governance live - policy drift detected and auto-remediated across 4 facilities simultaneously' },
    ],
    prerequisites: [
      'Phase 2 complete - 80 twins active, PdM and quality systems live',
      'Autonomous action governance framework approved by board and quality',
      'GxP validation of automated decision workflows (IQ/OQ/PQ completed)',
      'Change management and workforce upskilling programme completed',
    ],
    integrations: ['Supply chain / supplier portal', 'Regulatory submission systems', 'Customer quality portal', 'CDP / GHG Protocol carbon reporting'],
    deliverables: ['Autonomous operations platform', 'DPP implementation', 'Multi-site global governance', 'GxP continuous compliance system'],
  },
];

// ─── Deloitte Partnership ─────────────────────────────────────────────────────

export const deloitteData = {
  tagline: 'Your transformation partner from strategy to autonomous operations',
  description: 'The programme team combines OT/ICS engineering, life sciences manufacturing expertise, cybersecurity, and enterprise technology. Delivered across manufacturing clients globally - including pharma, biotech, and life sciences equipment manufacturers with GxP, FDA, and IEC 62443 compliance requirements.',

  phaseServices: [
    {
      phase: 'Foundation (0–6 months)',
      color: '#F5A623',
      icon: 'layers',
      services: [
        { name: 'OT Maturity Assessment',      icon: 'search', desc: 'Benchmarked assessment of current OT state against life sciences industry peers with quantified gap analysis', duration: '4 weeks' },
        { name: 'Target Architecture Design',  icon: 'layers',  desc: 'Reference architecture tailored to the manufacturing environment with GxP compliance, IEC 62443 zoning, and cloud connectivity built in', duration: '6 weeks' },
        { name: 'OT Security Assessment',      icon: 'shield',  desc: 'IEC 62443 gap analysis, network segmentation review, zero-trust OT access roadmap', duration: '6 weeks' },
        { name: 'Asset Discovery & CMDB',      icon: 'database', desc: 'Deployment and tuning of passive OT discovery with GxP inventory qualification across all facilities', duration: '8 weeks' },
      ],
    },
    {
      phase: 'Intelligence (6–18 months)',
      color: '#005EB8',
      icon: 'cpu',
      services: [
        { name: 'Digital Twin Activation',    icon: 'cpu', desc: 'Twin modelling, data pipeline build, behavioural baseline - using our Twin Activate™ accelerator', duration: '12 weeks' },
        { name: 'Predictive Maintenance',     icon: 'wrench', desc: 'ML model development, sensor integration, alert workflow - pre-validated for GxP environments', duration: '10 weeks' },
        { name: 'GxP Digital Thread',          icon: 'git-merge', desc: 'FDA 21 CFR Part 11 compliant data governance, electronic batch records, and full audit-trail framework', duration: '8 weeks' },
        { name: 'Carbon & Sustainability Twin',icon: 'leaf',  desc: 'Scope 1/2/3 measurement framework with closed-loop optimisation using our Carbon Lens™ platform', duration: '10 weeks' },
      ],
    },
    {
      phase: 'Autonomy (18–36 months)',
      color: '#12B3A8',
      icon: 'bot',
      services: [
        { name: 'Autonomous Ops Platform',    icon: 'bot', desc: 'Orchestration, self-healing workflows, and human-in-loop governance framework with GxP sign-off', duration: '16 weeks' },
        { name: 'Factory Copilot Deploy',      icon: 'zap', desc: 'LLM over the operational graph - natural-language factory intelligence, compliant with data privacy requirements', duration: '8 weeks' },
        { name: 'Global Platform Governance', icon: 'globe', desc: 'Multi-site rollout, StackSets deployment, global policy enforcement with drift detection', duration: '20 weeks' },
        { name: 'Operate & Optimise',         icon: 'settings', desc: 'Managed operations, continuous model improvement, KPI measurement, and quarterly value reviews', duration: 'Ongoing' },
      ],
    },
  ],

  differentiators: [
    { icon: 'users', title: 'OT + IT + Strategy. One Team.', desc: 'No handoffs between OT engineering, cyber, cloud architecture, and business strategy. One integrated Deloitte team owns the full transformation journey.' },
    { icon: 'flask-conical', title: 'Life Sciences Manufacturing Depth', desc: 'Dedicated GxP, FDA 21 CFR Part 11, and EudraLex Annex 11 expertise. Completed OT transformations in pharma, biotech, and life sciences equipment manufacturing with the same compliance profile.' },
    { icon: 'zap', title: 'Proven Accelerators Cut Time to Value', desc: 'OT Clarity™ for asset discovery, Twin Activate™ for digital twin deployment, GxP DataGuard™ for data governance, and Carbon Lens™ for sustainability - pre-built and pre-validated to reduce delivery time compared to starting from scratch.' },
    { icon: 'globe', title: 'Global Scale, Local Delivery', desc: 'Practitioners available globally including all major manufacturing regions. Global architecture, local implementation expertise, consistent delivery standards.' },
  ],

  accelerators: [
    { name: 'OT Clarity™',      icon: 'search', desc: 'Asset discovery and visualisation accelerator - deployed and delivering insights in under 2 weeks, zero production impact' },
    { name: 'Twin Activate™',   icon: 'cpu', desc: 'Digital twin activation framework with 40+ pre-built asset twin templates for pharma, biotech, and process manufacturing' },
    { name: 'GxP DataGuard™',  icon: 'shield', desc: 'FDA 21 CFR Part 11 / Annex 11 compliant data governance and audit trail framework - pre-validated for life sciences' },
    { name: 'Carbon Lens™',     icon: 'leaf',  desc: 'Scope 1/2/3 measurement and closed-loop carbon twin platform with EU Taxonomy and CDP reporting integration' },
  ],
};

// ─── Maturity Journey (Visibility → Autonomy) ─────────────────────────────────
// Based on "From Asset to Autonomous Factory" 5-step framework

export const otMaturitySteps = [
  {
    id: 'visibility',
    number: 1,
    title: 'Asset Visibility',
    icon: 'eye',
    tagline: 'What exists at all?',
    color: '#F5A623',
    bg: '#FFFBEB',
    goal: 'Complete transparency over all OT assets and systems - making the invisible factory visible.',
    activities: [
      'OT Discovery & Passive Asset Scanning',
      'Automated Device Recognition & Fingerprinting',
      'CMDB Auto-Population (purdue_level, fda_class, risk_score, firmware)',
      'Asset Classification & Normalisation (30+ attributes captured)',
      'Network Topology & Communication Path Mapping',
    ],
    tools: ['Claroty xDome', 'Nozomi Networks', 'OT Asset CMDB', 'Protocol Analyser'],
    businessValue: 'Transparency & Security - you know what you have, where it is, and what risk it carries.',
    exampleTitle: 'From Unknown to Known - Asset Discovery in Weeks',
    example: 'Hundreds of previously unknown OT devices discovered across manufacturing sites - zero production impact, passive-only discovery.',
    metric: 'High Asset Coverage',
    metricColor: '#F5A623',
  },
  {
    id: 'context',
    number: 2,
    title: 'Operational Context',
    icon: 'network',
    tagline: 'How does it all connect?',
    color: '#6366F1',
    bg: '#F0F0FF',
    goal: 'Understanding asset relationships, criticality scoring, and the full dependency graph across OT and IT.',
    activities: [
      'Asset Relationships & Network Topology Graph',
      'Criticality & Business Impact Scoring per Asset',
      'Location & Production Line Assignment',
      'OT-IT Context Mapping & Dependency Analysis',
      'Risk & Vulnerability Assessment with Exploitability Scoring',
    ],
    tools: ['ServiceNow OTSM', 'Operational Graph DB', 'Risk Scoring Engine', 'CMDB Relationship Maps'],
    businessValue: 'Better Decisions - every maintenance, security, and investment decision informed by full operational context.',
    exampleTitle: 'Every Asset Scored, Every Dependency Mapped',
    example: 'Control server auto-classified High Criticality - production line dependency identified, maintenance window prioritised accordingly.',
    metric: 'Full Risk Scoring',
    metricColor: '#6366F1',
  },
  {
    id: 'workflow',
    number: 3,
    title: 'Workflow Intelligence',
    icon: 'git-branch',
    tagline: 'How do we respond automatically?',
    color: '#005EB8',
    bg: '#EAF4FF',
    goal: 'Standardised, automated OT service and change processes - closing the gap between OT floor and IT service desk.',
    activities: [
      'Incident, Problem & Change Management (OT-native)',
      'Automated Alert Escalation & Smart Routing to Correct Team',
      'Runbooks & Standard Operating Procedures (auto-triggered)',
      'OT-IT Team Integration & Collaboration Workflows',
      'Self-Service Portals & Guided Troubleshooting Flows',
    ],
    tools: ['ServiceNow ITSM/OTSM', 'Runbook Automation Engine', 'Knowledge Base', 'SAP PM Integration'],
    businessValue: 'Faster Response - automated triage and routing materially reduce mean time to resolution.',
    exampleTitle: 'From Alert to Work Order in Minutes',
    example: 'High Vibration alert on Pump 12 → auto-routed to Maintenance Team → Work Order created in SAP within minutes, no phone calls needed.',
    metric: 'MTTR Reduced',
    metricColor: '#005EB8',
  },
  {
    id: 'excellence',
    number: 4,
    title: 'Operational Excellence',
    icon: 'bar-chart-2',
    tagline: 'How do we continuously optimise?',
    color: '#12B3A8',
    bg: '#E6FAF8',
    goal: 'Higher availability, operational efficiency, and continuously lower cost-per-unit produced across all facilities.',
    activities: [
      'Real-Time Performance Monitoring & OEE/MTTR/Downtime KPIs',
      'Predictive Maintenance & Condition-Based Monitoring',
      'Root Cause Analysis (RCA) Workflows with Full Context',
      'Capacity & Spare Parts Optimisation',
      'Continuous Improvement Loops with Feedback to Processes',
    ],
    tools: ['OEE Dashboard', 'Predictive Analytics Platform', 'RCA Engine', 'SAP PM/EAM', 'Digital Ops Centre'],
    businessValue: 'Higher Efficiency - measurable OEE gains, fewer unplanned stoppages, lower maintenance spend per unit.',
    exampleTitle: 'Predictive Alert Prevents Production Loss',
    example: 'Motor availability trending down → predictive alert 48 hrs early → optimal maintenance window booked → production loss avoided.',
    metric: 'OEE Improved · Downtime Reduced',
    metricColor: '#12B3A8',
  },
  {
    id: 'autonomy',
    number: 5,
    title: 'Digital Twin & Autonomy',
    icon: 'bot',
    tagline: 'How do we simulate and control autonomously?',
    color: '#003B73',
    bg: 'rgba(0,59,115,0.04)',
    goal: 'Autonomous, self-optimising and resilient factory operations - the plant monitors, decides, and improves itself.',
    activities: [
      'Real-Time Digital Twin & Live 3D Simulation',
      'AI/ML Models for Autonomous Operational Decisions',
      'Closed-Loop Automation & Self-Healing Workflows',
      'Scenario Planning, What-If Analysis & Impact Simulation',
      'Continuous Learning & Adaptive Control Systems',
    ],
    tools: ['Azure Digital Twins', 'ML Platform', 'Factory Copilot (LLM)', 'Orchestration Engine', 'Simulation Runtime'],
    businessValue: 'Autonomous Factory - the plant monitors, decides, and continuously optimises itself with minimal human intervention.',
    exampleTitle: 'Autonomous Scheduling Improves Throughput',
    example: 'Digital Twin simulates alternative shift pattern across production lines → projects throughput gain → auto-applied after one-click human approval.',
    metric: 'Increasing Autonomy',
    metricColor: '#003B73',
  },
];

// ─── OT Visibility Value Pillars ──────────────────────────────────────────────
// Based on "Security is only the beginning - OT Visibility creates value for the whole factory"

export const otValuePillars = [
  {
    id: 'ops',
    icon: 'activity',
    title: 'Operations Excellence',
    subtitle: 'Better real-time decisions',
    example: 'Real-time condition monitoring of all plant assets with instant anomaly detection, prioritisation, and response dispatch.',
    effect: 'Faster response times, fewer production disruptions, greater operational stability across all shifts.',
    stat: 'OEE +10–20%',
    statColor: '#005EB8',
    enabledAtStep: 3,
    color: '#005EB8',
  },
  {
    id: 'maintenance',
    icon: 'wrench',
    title: 'Maintenance Optimisation',
    subtitle: 'From reactive to proactive',
    example: 'Predictive condition monitoring enables maintenance to be scheduled before failure - not called after breakdown.',
    effect: 'Fewer unplanned failures, extended asset lifespan, significantly reduced emergency maintenance callouts.',
    stat: 'Downtime -20–40%',
    statColor: '#F5A623',
    enabledAtStep: 4,
    color: '#F5A623',
  },
  {
    id: 'automation',
    icon: 'settings',
    title: 'Automation & Efficiency',
    subtitle: 'Less manual work, faster throughput',
    example: 'Automated workflows for incidents, change requests, and approvals - guided runbooks replace manual triage entirely.',
    effect: 'Higher process efficiency, fewer human errors, faster end-to-end cycle times on every OT operation.',
    stat: 'Maintenance Costs -15–30%',
    statColor: '#12B3A8',
    enabledAtStep: 3,
    color: '#12B3A8',
  },
  {
    id: 'performance',
    icon: 'line-chart',
    title: 'Performance & Profitability',
    subtitle: 'Higher output, lower total cost',
    example: 'Continuous KPI tracking (OEE, MTTR, Downtime) feeds improvement loops - gains compound month over month.',
    effect: 'Measurable OEE gains, fewer costly breakdowns, better cost-per-unit control across all production lines.',
    stat: 'Tech Productivity +20–30%',
    statColor: '#6366F1',
    enabledAtStep: 4,
    color: '#6366F1',
  },
  {
    id: 'compliance',
    icon: 'check-circle',
    title: 'Governance & Compliance',
    subtitle: 'Traceable, auditable, defensible',
    example: 'Full audit trail on all asset changes and access events - NIS2, GxP, and IEC 62443 compliance tracked continuously.',
    effect: 'Easy regulatory audits, clear accountability chains, full compliance confidence at any point in time.',
    stat: 'Compliance 100% Auditable',
    statColor: '#10B981',
    enabledAtStep: 2,
    color: '#10B981',
  },
  {
    id: 'future',
    icon: 'cpu',
    title: 'Digital Twin & Future Readiness',
    subtitle: 'The non-negotiable foundation',
    example: 'No digital twin, no AI, no autonomous operations without complete asset visibility - it is the prerequisite for everything.',
    effect: 'Simulation, scenario planning, and continuous self-optimisation driven by operational truth.',
    stat: 'Risk Reduction -30–60%',
    statColor: '#D64545',
    enabledAtStep: 5,
    color: '#D64545',
  },
];

// ─── Digital Twin Prerequisites Formula ───────────────────────────────────────
// Based on "From OT Visibility to Digital Twin" framework (Claroty + ServiceNow + SAP)

export const digitalTwinPrereqs = [
  { id: 'visibility', label: 'Full Visibility',        icon: 'eye',  desc: 'All OT assets discovered, classified, and streaming real-time telemetry.', color: '#F5A623' },
  { id: 'data',       label: 'Reliable Data',          icon: 'database',  desc: 'High-quality historical and real-time data normalised and validated from all Purdue levels.', color: '#6366F1' },
  { id: 'context',    label: 'Context & Relationships', icon: 'network', desc: 'Deep asset relationship graph, process dependencies, and operational topology understood.', color: '#005EB8' },
  { id: 'integration',label: 'Integrated Processes',   icon: 'workflow',  desc: 'Incidents, maintenance, and workflows end-to-end integrated across OT and IT systems.', color: '#12B3A8' },
  { id: 'governance', label: 'Governance & Trust',     icon: 'shield',  desc: 'Data security, access controls, compliance validation, and full audit trail active.', color: '#10B981' },
  { id: 'analytics',  label: 'Analytics & Simulation', icon: 'bar-chart-2',  desc: 'AI/ML models, simulation environments, and decision engines trained on operational data.', color: '#003B73' },
];

// ─── Technology Platform Stack ────────────────────────────────────────────────
// Three-platform reference architecture (Claroty xDome + ServiceNow OTSM + SAP)

export const techStack = [
  {
    id: 'discovery',
    name: 'OT Asset Discovery',
    product: 'Claroty xDome',
    icon: 'search',
    color: '#F5A623',
    role: 'Foundation - See Everything',
    capabilities: [
      'OT Network & Asset Discovery (passive)',
      'Asset Context, Criticality & Risk Scoring',
      'Real-Time Events & Telemetry Collection',
      'Vulnerability Management & CVE Tracking',
    ],
    output: 'Complete OT asset inventory with 30+ attributes, vulnerability data, topology, and continuous telemetry',
  },
  {
    id: 'management',
    name: 'OT Service Management',
    product: 'ServiceNow OTSM',
    icon: 'workflow',
    color: '#005EB8',
    role: 'Intelligence - Act on Knowledge',
    capabilities: [
      'Incident & Event Management (OT-native)',
      'Change & Risk Management with Approval Flows',
      'Workflow & Orchestration (Runbooks / SOPs)',
      'CMDB + Time Series Data Integration',
    ],
    output: 'Automated OT processes, cross-team collaboration, full traceability from event to resolution',
  },
  {
    id: 'execution',
    name: 'Maintenance Management',
    product: 'SAP S/4HANA',
    icon: 'settings',
    color: '#12B3A8',
    role: 'Execution - Deliver Outcomes',
    capabilities: [
      'Maintenance Planning & Work Order Management',
      'Technical Execution & Resource Scheduling',
      'Material, Spare Parts & Cost Tracking',
      'GxP-compliant Equipment History',
    ],
    output: 'Optimised maintenance execution with full cost, resource, and compliance tracking',
  },
];

// ─── NIS2 / Cybersecurity Compliance Gap Analysis ─────────────────────────────
// Maturity levels: 0=Absent, 1=Initial, 2=Repeatable, 3=Defined, 4=Managed, 5=Optimised

export const nis2Domains = [
  {
    domain: 'Risk Management',
    color: '#F5A623',
    icon: 'alert-triangle',
    items: [
      { label: 'Risk Analysis',                  it: 3, ot: 2, target: 4 },
      { label: 'Information Security Policies',  it: 2, ot: 1, target: 4 },
      { label: 'Target-Performance Comparison',  it: 2, ot: 1, target: 4 },
    ],
  },
  {
    domain: 'Security Management',
    color: '#D64545',
    icon: 'shield',
    items: [
      { label: 'Cryptography & Encryption',      it: 3, ot: 2, target: 4 },
      { label: 'Identity & Access Management',   it: 4, ot: 3, target: 5 },
      { label: 'Multi-Factor Authentication',    it: 4, ot: 2, target: 5 },
      { label: 'Asset Management',               it: 4, ot: 2, target: 5 },
      { label: 'Vulnerability Management',       it: 3, ot: 2, target: 4 },
      { label: 'Secure Communication',           it: 3, ot: 2, target: 4 },
    ],
  },
  {
    domain: 'Incident Management',
    color: '#6366F1',
    icon: 'activity',
    items: [
      { label: 'Incident Detection',             it: 4, ot: 3, target: 5 },
      { label: 'Incident Categorisation',        it: 4, ot: 3, target: 5 },
      { label: 'Incident Reporting',             it: 3, ot: 1, target: 4 },
      { label: 'Incident Postprocessing',        it: 3, ot: 2, target: 5 },
    ],
  },
  {
    domain: 'Resilience Management',
    color: '#10B981',
    icon: 'zap',
    items: [
      { label: 'Business Impact Analysis',       it: 2, ot: 0, target: 4 },
      { label: 'Business Continuity Mgmt',       it: 2, ot: 0, target: 4 },
      { label: 'Backup Management',              it: 4, ot: 3, target: 4 },
      { label: 'Crisis Management',              it: 2, ot: 2, target: 4 },
      { label: 'Disaster Recovery',              it: 2, ot: 0, target: 4 },
    ],
  },
];

// ─── Discovered Asset Schema ──────────────────────────────────────────────────
// The 30+ fields auto-populated by passive OT asset discovery

export const otAssetFields = [
  { field: 'asset_id',                    category: 'Identity',     desc: 'Unique identifier auto-generated at discovery' },
  { field: 'device_name',                 category: 'Identity',     desc: 'Hostname / label resolved from network traffic' },
  { field: 'manufacturer',                category: 'Identity',     desc: 'Hardware manufacturer auto-fingerprinted' },
  { field: 'model',                       category: 'Identity',     desc: 'Device model detected from traffic signatures' },
  { field: 'serial_number',               category: 'Identity',     desc: 'Serial number extracted from protocol responses' },
  { field: 'purdue_level',                category: 'OT Context',   desc: 'Purdue Model level (L0–L4) auto-classified' },
  { field: 'device_category',             category: 'OT Context',   desc: 'Category: PLC / HMI / Sensor / Server / Network' },
  { field: 'device_type',                 category: 'OT Context',   desc: 'Specific device type (e.g. Bioreactor Controller)' },
  { field: 'device_type_family',          category: 'OT Context',   desc: 'Asset family grouping for fleet management' },
  { field: 'fda_class',                   category: 'Compliance',   desc: 'FDA device classification (Class I / II / III)' },
  { field: 'phi',                         category: 'Compliance',   desc: 'Protected Health Information flag for GxP assets' },
  { field: 'risk_score',                  category: 'Risk',         desc: 'Composite risk score (0–100) computed in real-time' },
  { field: 'ip_list',                     category: 'Network',      desc: 'All IP addresses observed on the asset' },
  { field: 'mac_list',                    category: 'Network',      desc: 'MAC addresses for network identity correlation' },
  { field: 'network_list',                category: 'Network',      desc: 'VLAN/subnet membership across all interfaces' },
  { field: 'connection_type_list',        category: 'Network',      desc: 'Protocol connections: EtherNet/IP, Profinet, OPC-UA…' },
  { field: 'os_name',                     category: 'Software',     desc: 'Operating system name (Windows, Linux, VxWorks…)' },
  { field: 'os_version',                  category: 'Software',     desc: 'OS version - used for patch compliance tracking' },
  { field: 'software_or_firmware_version',category: 'Software',     desc: 'Firmware/software version for CVE matching' },
  { field: 'hw_version',                  category: 'Software',     desc: 'Hardware revision for lifecycle management' },
  { field: 'location',                    category: 'Physical',     desc: 'Physical location: building, floor, production line' },
  { field: 'site_name',                   category: 'Physical',     desc: 'Manufacturing site (e.g. Primary Site, APAC Site)' },
  { field: 'edge_locations',              category: 'Physical',     desc: 'Edge compute association for local processing' },
  { field: 'ap_location_list',            category: 'Physical',     desc: 'Wireless access point location context' },
  { field: 'cmms_asset_tag',              category: 'Integration',  desc: 'CMMS/EAM asset tag for SAP PM / Maximo sync' },
  { field: 'dashboard_url',               category: 'Integration',  desc: 'Direct deep-link to asset operational dashboard' },
  { field: 'collection_interfaces',       category: 'Integration',  desc: 'Active collection interfaces (SPAN, SNMP, REST…)' },
  { field: 'connector_devices',           category: 'Integration',  desc: 'Connected upstream/downstream devices' },
  { field: 'retired',                     category: 'Lifecycle',    desc: 'Retirement flag - tracks end-of-life assets' },
  { field: 'labels',                      category: 'Lifecycle',    desc: 'Custom tags for grouping, filtering, and policy' },
];

// ─── Sample Discovered Asset Inventory ────────────────────────────────────────
// Generic representation of a real manufacturing site OT asset population

export const sampleAssets = [
  { name: 'Production Control Server A',    type: 'Manufacturing Control Server', site: 'Primary Site', purdue: 'L3', risk: 72, os: 'Windows Server 2019', status: 'Active',   cve: 3 },
  { name: 'Production Control Server B',    type: 'Manufacturing Control Server', site: 'Primary Site', purdue: 'L3', risk: 68, os: 'Windows Server 2019', status: 'Active',   cve: 3 },
  { name: 'Lab Equipment Server (Line A)',   type: 'Lab Equipment Control Server', site: 'Primary Site', purdue: 'L2', risk: 55, os: 'Windows Server 2016', status: 'Active',   cve: 7 },
  { name: 'Lab Equipment Server (Line B)',   type: 'Lab Equipment Control Server', site: 'Primary Site', purdue: 'L2', risk: 55, os: 'Windows Server 2016', status: 'Active',   cve: 7 },
  { name: 'Lab Equipment Server (Line C)',   type: 'Lab Equipment Control Server', site: 'Primary Site', purdue: 'L2', risk: 60, os: 'Windows Server 2016', status: 'Active',   cve: 5 },
  { name: 'Production DB Server (Primary)', type: 'PostgreSQL Database Server',   site: 'Primary Site', purdue: 'L3', risk: 45, os: 'Linux (Debian 11)',    status: 'Active',   cve: 1 },
  { name: 'Production DB Server (Replica)', type: 'PostgreSQL Database Server',   site: 'Primary Site', purdue: 'L3', risk: 45, os: 'Linux (Debian 11)',    status: 'Active',   cve: 1 },
  { name: 'Statistics DB Server',           type: 'Analytics Database Server',    site: 'Primary Site', purdue: 'L3', risk: 38, os: 'Linux (Debian 11)',    status: 'Active',   cve: 0 },
  { name: 'Virtualisation Host 1',          type: 'Compute Host (VMware)',        site: 'Primary Site', purdue: 'L3', risk: 40, os: 'VMware ESXi 7.0',      status: 'Active',   cve: 2 },
  { name: 'Virtualisation Host 2',          type: 'Compute Host (VMware)',        site: 'Primary Site', purdue: 'L3', risk: 40, os: 'VMware ESXi 7.0',      status: 'Active',   cve: 2 },
  { name: 'Remote Access Server 1',         type: 'RDP Terminal Server',          site: 'Primary Site', purdue: 'L3', risk: 82, os: 'Windows Server 2022',  status: 'Active',   cve: 0 },
  { name: 'Remote Access Server 2',         type: 'RDP Terminal Server',          site: 'Primary Site', purdue: 'L3', risk: 82, os: 'Windows Server 2022',  status: 'Active',   cve: 0 },
  { name: 'Network Services Server',        type: 'DHCP / DNS Server',            site: 'Primary Site', purdue: 'L3', risk: 65, os: 'Linux (Ubuntu 22)',    status: 'Active',   cve: 1 },
  { name: 'Backup Storage NAS 1',           type: 'Network Attached Storage',     site: 'Primary Site', purdue: 'L3', risk: 35, os: 'Synology DSM 7',       status: 'Active',   cve: 0 },
  { name: 'APAC DB Server (Primary)',       type: 'PostgreSQL Database Server',   site: 'APAC Site',    purdue: 'L3', risk: 58, os: 'Linux (Debian 11)',    status: 'Active',   cve: 2 },
  { name: 'APAC DB Server (Replica)',       type: 'PostgreSQL Database Server',   site: 'APAC Site',    purdue: 'L3', risk: 58, os: 'Linux (Debian 11)',    status: 'Active',   cve: 2 },
  { name: 'APAC Virtualisation Host',       type: 'Compute Host (VMware)',        site: 'APAC Site',    purdue: 'L3', risk: 44, os: 'VMware ESXi 7.0',      status: 'Active',   cve: 1 },
  { name: 'Engineering Workstation (Dev 1)',type: 'Engineering Workstation',      site: 'Primary Site', purdue: 'L3', risk: 70, os: 'Windows 11 Pro',       status: 'Active',   cve: 4 },
  { name: 'Engineering Workstation (Dev 2)',type: 'Engineering Workstation',      site: 'Primary Site', purdue: 'L3', risk: 70, os: 'Windows 11 Pro',       status: 'Active',   cve: 4 },
  { name: 'Label Print Server',             type: 'Print Server',                 site: 'Primary Site', purdue: 'L3', risk: 30, os: 'Windows Server 2019',  status: 'Active',   cve: 0 },
  { name: 'Proxy & Time Server (Node 1)',   type: 'Network Services Server',      site: 'Primary Site', purdue: 'L3', risk: 50, os: 'Linux (Debian 11)',    status: 'Active',   cve: 1 },
  { name: 'Proxy & Time Server (Node 2)',   type: 'Network Services Server',      site: 'Primary Site', purdue: 'L3', risk: 50, os: 'Linux (Debian 11)',    status: 'Active',   cve: 1 },
  { name: 'CNC Backup & Archive Server',    type: 'Archival Server',              site: 'Primary Site', purdue: 'L3', risk: 42, os: 'Linux (Debian 11)',    status: 'Active',   cve: 0 },
  { name: 'Robot Control Server (Line A)',  type: 'Robotics Control Server',      site: 'Primary Site', purdue: 'L2', risk: 88, os: 'Windows 10 LTSC',      status: 'Active',   cve: 6 },
  { name: 'Robot Control Server (Line B)',  type: 'Robotics Control Server',      site: 'Primary Site', purdue: 'L2', risk: 88, os: 'Windows 10 LTSC',      status: 'Active',   cve: 6 },
  { name: 'Vision / Camera Server',         type: 'Quality Inspection Server',    site: 'Primary Site', purdue: 'L2', risk: 65, os: 'Windows 10 Pro',       status: 'Active',   cve: 2 },
  { name: 'End-of-Line Test Server',        type: 'Product Test Server',          site: 'Primary Site', purdue: 'L2', risk: 55, os: 'Windows 10 LTSC',      status: 'Active',   cve: 3 },
  { name: 'Dev & Test Server (APT)',         type: 'Development Server',           site: 'Primary Site', purdue: 'L3', risk: 35, os: 'Linux (Debian 12)',    status: 'Active',   cve: 0 },
  { name: 'Control Server (Decommissioned)',type: 'Manufacturing Control Server', site: 'Primary Site', purdue: 'L2', risk: 95, os: 'Windows XP Embedded',  status: 'Retired',  cve: 22 },
  { name: 'Packaging Line Server (Legacy)', type: 'Manufacturing Control Server', site: 'Primary Site', purdue: 'L2', risk: 91, os: 'Windows 7 Embedded',   status: 'Retired',  cve: 18 },
];
